### ISSUE TITLE
ادیت mtu 

### ISSUE THREAD

**Issue by kalilovers** [Azumi67/6TO4-GRE-IPIP-SIT#1]
سلام خسته نباشید ممنون از زحماتتون 
میتونید  یه تغییری تو اسکریپت مولتی private بدید 
موقع تنظیم mtu رو بالاتر از mtu خود سیستم قرار میده و چیزی که کار نمیکنه عملا . ادیت mtu هم نداره این اسکریپت . مثلا خود سرور 1472 کار میکنه حداکثر این 1480 میندازه باعث نوسان میشه

**Comment by Azumi67** [comment]
سلام مرسی. صبر کنید دارم به همین اسکریپت مولتی رو اضافه میکنم با ادیت mtu . به اون هم بعدا اضافه میکنم. فعلا دارم تستش میکنم و باگ هاش رو میگیرم.

**Comment by kalilovers** [comment]
> سلام مرسی. صبر کنید دارم به همین اسکریپت مولتی رو اضافه میکنم با ادیت mtu . به اون هم بعدا اضافه میکنم. فعلا دارم تستش میکنم و باگ هاش رو میگیرم.

تشکر پس اینطوری خیلی بهتر میشه . چون واقعا به اسکریپت جدا نیاز نیست برای یدونه مولتی private . انیکست که خودش مولتی حساب میشه تو همین سینگل هم اوکیه لطف میکنید خسته نباشید

**Comment by Azumi67** [comment]
چندین سرور اضافه شد. بررسی کنید

**Comment by kalilovers** [comment]
اره الان دارم تست میکنم متد هارو خیلی ممنون دیدم
