### ISSUE TITLE
مشکل در اینترفیس 

### ISSUE THREAD

**Issue by Matialz7** [Azumi67/6TO4-GRE-IPIP-SIT#10]
این ارور از چی میتونه باشه ؟!
چجوری میتونم اینترفیس رو پاک کنم و از اول ادد کنم ؟!
add tunnel "sit0" failed: No buffer space available
Cannot find device "azumi2"
Cannot find device "azumi2"

**Comment by Azumi67** [comment]
شما قبلا یک اینترفیس با این نام دارید. اول اون رو پاک کنید و سپس دوباره مجدد کانفیگ کنید . با ip a پیداش کنید و از قسمت مربوطه پاکش کنید .

**Comment by Matialz7** [comment]
چطوری پاکش کنم ؟!

**Comment by Azumi67** [comment]
شما با ip a نام‌ اینترفیس رو ببینید و بعد
 ip link delete نام اینترفیس
یا از طریق اسکریپت پاک کنید .
