### ISSUE TITLE
بعضی سرورا کارت شبکه -ip 192.168.10.21

### ISSUE THREAD

**Issue by jadopcb** [Azumi67/6TO4-GRE-IPIP-SIT#100]
سلام تشکر و سپاس فراوان

یک سرور دارم که
قبلا مشخصات فرستاد بودم

از طریق ip داخلیشن  تونستم بین ایران خارج اتصال برقرا کنم و پینگ بده -اما به صورت زیر

server iran

192.168.10.21  --->> ip khargh    
با ای پی  سرور ایران اتصال برقرا نمیشد( اما ای پی داخلیش میشه )

sever kharje

ip server iran ---- ip kharj server 
به روش عادی اتصال برقرا میشه

اینجوری تونستم پینگ بین ایران  و  خارج     با روش 1 به 10 بگیریم

اما مشکل اینکه وقتی ای پی سرور  ایران میزارم  وصل نمیشه!
 
 لطفا راهنمایی میکنین چکار کنیم

دسترسی م لازمه بفرمایین

**Comment by Azumi67** [comment]
سلام. سوالتون کمی مبهم است . لوکال ایپی اون روشی که انجام دادید چه میباشد ؟

**Comment by jadopcb** [comment]
روش 5 سرور ایران .و 10 خارج

webPublic :2.xxx.xx.xx.xx
webPrivate :192.168.10.31

![01](https://github.com/user-attachments/assets/317669b4-385b-4a89-b008-d8287d77a6f0)
![01](https://github.com/user-attachments/assets/758b5400-2c6d-4287-a6b9-ddfbb09411f2)

**Comment by Azumi67** [comment]
خب لطفا پورت فوروارد های دیگری مثل socat هم تست کنید و ببینید با اون هم همین مشکل است یا خیر. ایپی پرایوت را در فایروال خود هم اضافه کنید.
