### ISSUE TITLE
عدم اجرای تانل روی مجازی ساز OpenVZ

### ISSUE THREAD

**Issue by javad48** [Azumi67/6TO4-GRE-IPIP-SIT#101]
سلام .من یه سرور تهیه کردم که متاسفانه مجازی ساز OpenVZ هست
هرکاری کدم تانل روش اجرا نمیشه.نمیدونم مشکل از کجاست
Enter Kharej IPV4 address: 
Enter IRAN IPV4 address: 
add tunnel "sit0" failed: No such device
Cannot find device "azumi"
Cannot find device "azumi"
╰─────────────────────────────────────────────────────────╯
─────────────────────────────────────────────────────────
✨ Adding commands...
─────────────────────────────────────────────────────────
Do you want to set the MTU [6to4]? (yes/no): ✘ Error: 
Program interrupted. Exiting...
root@linux:~# lsmod | grep -w sit
sit                     4242  -2
tunnel4                 4242  -2 sit,ipip
ip_tunnel               4242  -2 sit,ipip,ip_gre

**Comment by kalilovers** [comment]
سلام این به دلایل مختلفی میتونه باشه یا OpenVZ  شما قدیمی هستش و پشتیبانی نمیکنه یا ماژول هاش فعال نشده و محدود شده توسط ارایه دهنده .

**Comment by javad48** [comment]
> > سلام .من یه سرور تهیه کردم که متاسفانه مجازی ساز OpenVZ هست هرکاری کدم تانل روش اجرا نمیشه.نمیدونم مشکل از کجاست Enter Kharej IPV4 address: Enter IRAN IPV4 address: add tunnel "sit0" failed: No such device Cannot find device "azumi" Cannot find device "azumi" ╰─────────────────────────────────────────────────────────╯ ───────────────────────────────────────────────────────── ✨ Adding commands... ───────────────────────────────────────────────────────── Do you want to set the MTU [6to4]? (yes/no): ✘ Error: Program interrupted. Exiting... root@linux:~# lsmod | grep -w sit sit 4242 -2 tunnel4 4242 -2 sit,ipip ip_tunnel 4242 -2 sit,ipip,ip_gre
> 
> > 
> 
> سلام این به دلایل مختلفی میتونه باشه یا OpenVZ شما قدیمی هستش و پشتیبانی نمیکنه یا ماژول هاش فعال نشده و محدود شده توسط ارایه دهنده .
> 
> اگه به تنظیمات سرور دسترسی دارید با این دستور ببینید فعاله یه سری ماژولا یا نه : lsmod | grep -e sit -e gre -e ipip
> 
> اگر فعال نبود باید فعال کنید و اینکه به ارایه دهنده سرورتون هم بگید . به احتمال زیاد یکی از همین موارد باشه

ممنونم از جوابتون .بله بخاطر محدودیت هایی از سمت ارایه دهنده بود.مشکل زیاد داشت کرنل هم اپدیت نبود و .... .اما بالاخره با تیکت و ...یه روش روش کارکرد.مرسی.
با bbr هم مشکلات زیادی داره ...
