### ISSUE TITLE
2 تا خارج و یه ایران 

### ISSUE THREAD

**Issue by Mohammadaminsdr** [Azumi67/6TO4-GRE-IPIP-SIT#102]
سلام وقت بخیر جدیدا به این مشکل خوردیم که دوتا خارج رو که تانل میزنیم به یه ایران هر دو پینگ میدم و همه چی اوکیه ولی وقتی تانل رو با گوست برقرار میکنیم سرور اولی بدون مشکل کار میکنه و دومی کار نمیکنه فایروال و ... رو هم چک کردیم ولی درست نمیشه خیلی عجیب شده برام خواستم بدونم مشکل از کجا میتونه باشه ممنون از شما

**Comment by Azumi67** [comment]
سلام این مشکل جدیدی نیست و برای یک سری از پروتکل ها اتفاق میوفته . حتما دقت کنید که پینگ بین دو سرور برقرار باشد و آی‌پی 4 و 6 فوروارد شود و پرایوت آی‌پی مربوطه بسته نباشد. از تانل یا پورت فوروارد های دیگری هم استفاده کنید و کانفیگ های مختلف را تست کنید . یکی از همین ها باید جواب دهد.
