### ISSUE TITLE
ایجاد تانل لوکال 

### ISSUE THREAD

**Issue by SasanKHZN** [Azumi67/6TO4-GRE-IPIP-SIT#103]
سلام ازومی یک سوالی دارم می شود تانلی ایجاد کرد که از چند ایپی 6 لوکال استفاده کنیم همراه ipsec
منظورم پرایوت ایپی همراه ایپی سک هست که چند ای پی 6 ایجاد کنه

**Comment by Azumi67** [comment]
سلام. اون همان additional ip است.

**Comment by SasanKHZN** [comment]
کجای منو هست

**Comment by Azumi67** [comment]
در IPsec به دلیل وجود مشکلاتی، additional ip حذف شده است.

**Comment by poumadesign** [comment]
سلام وقت بخیر

این چند روز روی هر سروی که نصب میکنم به جز سرور ایران با خطای زیر روبرو میشم:

Pinging failed: Command '['ping', '-c', '2', 'fd1d:fc98:b73e:b481::2']' returned non-zero exit status 2.
روی سرور ایران اصلا خطا نمیده

**Comment by Azumi67** [comment]
> سلام وقت بخیر
> 
> این چند روز روی هر سروی که نصب میکنم به جز سرور ایران با خطای زیر روبرو میشم:
> 
> Pinging failed: Command '['ping', '-c', '2', 'fd1d:fc98:b73e:b481::2']' returned non-zero exit status 2. روی سرور ایران اصلا خطا نمیده

اون برای پینگ دو لوکال بین دو سرور است . خطای خاصی نیست. شما وقتی سرور‌خارج را کانفیگ میکنید ، هنوز سرور‌ایران کانفیگ نشده است و برای همین هم پینگ لوکال بین دو سرور برقرار نمیشود و چنین خطایی میگیرید.

**Comment by poumadesign** [comment]
تشکر

> > سلام وقت بخیر
> > این چند روز روی هر سروی که نصب میکنم به جز سرور ایران با خطای زیر روبرو میشم:
> > Pinging failed: Command '['ping', '-c', '2', 'fd1d:fc98:b73e:b481::2']' returned non-zero exit status 2. روی سرور ایران اصلا خطا نمیده
> 
> اون برای پینگ دو لوکال بین دو سرور است . خطای خاصی نیست. شما وقتی سرور‌خارج را کانفیگ میکنید ، هنوز سرور‌ایران کانفیگ نشده است و برای همین هم پینگ لوکال بین دو سرور برقرار نمیشود و چنین خطایی میگیرید.
 
تشکر ولی جدیدا روی هر سروری کانفیگ میکنیم تانل اجرا نمیشه و عملا هیچ کانفیگی جواب نمیده

**Comment by Azumi67** [comment]
> تشکر
> 
> > > سلام وقت بخیر
> > > این چند روز روی هر سروی که نصب میکنم به جز سرور ایران با خطای زیر روبرو میشم:
> > > Pinging failed: Command '['ping', '-c', '2', 'fd1d:fc98:b73e:b481::2']' returned non-zero exit status 2. روی سرور ایران اصلا خطا نمیده
> > 
> > 
> > اون برای پینگ دو لوکال بین دو سرور است . خطای خاصی نیست. شما وقتی سرور‌خارج را کانفیگ میکنید ، هنوز سرور‌ایران کانفیگ نشده است و برای همین هم پینگ لوکال بین دو سرور برقرار نمیشود و چنین خطایی میگیرید.
> 
> تشکر ولی جدیدا روی هر سروری کانفیگ میکنیم تانل اجرا نمیشه و عملا هیچ کانفیگی جواب نمیده

باید روش های مختلفی که قرار دادم تست کنید یا صبر کنید آپدیت eoip بیاد

**Comment by kalilovers** [comment]
> سلام وقت بخیر
> 
> این چند روز روی هر سروی که نصب میکنم به جز سرور ایران با خطای زیر روبرو میشم:
> 
> Pinging failed: Command '['ping', '-c', '2', 'fd1d:fc98:b73e:b481::2']' returned non-zero exit status 2. روی سرور ایران اصلا خطا نمیده

سلام احتمالا از متد ساده sit , 6to4 استفاده میکنید و خود sit تو اغلب سرور ها از سمت فایروال لیمیت شده و طبیعیه کار نکنه ولی بعضی از روش های ترکیبی که تو اسکریپت هست حتی اگر از sit هم استفاده کرده باشن کار میکنن در کل بهتره از اون متد های ساده استفاده نکنید . سرور خارج هم خیلی مهم هستش تو محدودیت ها
