### ISSUE TITLE
خطای Handshake Tls

### ISSUE THREAD

**Issue by alamdari86** [Azumi67/6TO4-GRE-IPIP-SIT#106]
سلام و عرض ادب و خسته نباشید
من تانل GRE6 رو با دکو زدم
ولی الان چند روز هست برای بعضی از کاربرا وصل نمیشه ولی خطای handshake tls میده
امکان داره بخاطر اختلال روی تانل یا دکومودور باشه؟

در ضمن tls ندارم رو کانفیگ ها

**Comment by Azumi67** [comment]
سلام اول مطمئن بشید که ارتباط لوکال‌ برقرار هست . سپس اطمینان پیدا کنید که آی‌پی ایران شما بر روی اپراتور خاصی مشکل نداشته باشد . سپس نوع کانفیگ را عوض کنید و در نهایت تانل دیگری‌ را تست میکنید .

**Comment by alamdari86** [comment]
جالت اینه که وقتی restart xray میزنم حل میشه
مشکل میتونه از ورژن xray باشه؟ الان رو 1.8.4 هست
این مشکل 99درصد رو اندروید هست

**Comment by Azumi67** [comment]
> جالت اینه که وقتی restart xray میزنم حل میشه مشکل میتونه از ورژن xray باشه؟ الان رو 1.8.4 هست این مشکل 99درصد رو اندروید هست

بله فکر کنم باید ورژن دیگری تست کتید

**Comment by alamdari86** [comment]
سوال آخر و تمام
من ایپی های لوکال رو با دکو ست میکنم 
بجای دکومودور چی پیشنهاد میدید؟

**Comment by Azumi67** [comment]
میتونید از پروژه های مختلف استفاده کنید . همون doko هم مشکلی نداره. Haproxy هم خوبه
