### ISSUE TITLE
پینگ گرفتن از آیپی پشت دامنه

### ISSUE THREAD

**Issue by Kup1ng** [Azumi67/6TO4-GRE-IPIP-SIT#13]
سلام خدمت شما
خیلی ممنونم از پیگیری شما و کمک های شما
هیچوقت لطفتون را فراموش نمیکنیم
یک درخواست داشتم و این بود که میتونید توی قسمتی که برای هر تانل پینگ سرویس را فعال میکنه و میگه ایپی بقیه سرور هارو وارد کن کاری کنید که بهش دامنه بدیم و از ایپی پشت اون پینگ بگیره چون ما با هر تعویض ایپی مجبوریم کل این سیستم را یکبار پاک کنیم و از اول بزنیم
اگر زحمت این را بکشید واقعا لطف بزرگی میکنید

**Comment by Azumi67** [comment]
سلام . خوب به هر صورت باید سرور مقابل کانفیگ بشه . مثلا اگر‌ سرور خارج fqdn سرور‌ایران رو میدید و سرور ایران عوض بشه . شما میاین آی‌پی پشت دامنه رو عوض میکنید و بعد سرور‌ایران جدید را کانفیگ میکنید . سرور خارج هم باید کانفیگ بشه چون ریموت آی‌پی مهمه . بعدا که کار اسکریپت کامل بشه، در فکرش هستم که گزینه ویرایش را درست کنم که بشه این مشکل رو برطرف کرد .

**Comment by Kup1ng** [comment]
قطعا شما بهتر ما میدونید ، بله گزینه ویرایش خیلی نیازه
ممنون از پاسخگویی و زحماتتون
