### ISSUE TITLE
ایده

### ISSUE THREAD

**Issue by Saeedroshan1906** [Azumi67/6TO4-GRE-IPIP-SIT#14]
سلام خانم ازومی عزیز مرسی از اسکریپت خفنت من الان از گزینه geneve استفاده میکنم و میکسش کردم با تانل گاست ، موردی و که خواستم بگم خدمتت اینه که یه اپدیت توی اسکریپت ایجاد کن و ایپی های رندومی که تولید میکنه رو بیشتر کن چون من روی چندین سرور تیت کردم تقریبا ایپی یکسان میده و این به مرور زمان در شبکه های محلی محدود میشه که مثلا ایپی ۸۰.۰۱.۱ دسترسی پیدا نکنه ، و اینکه گزینه اول که اکسترا هست به درستی کار نمیکنه موقع ایجاد خطا میزنه ، همچنین اگه بشه گزینه ای اضافه کنی که زمانی که اتصال محلی برقرار شد بشه از توی همون اسکریپت تانل هم انجام بشه مرسی از لطفت

**Comment by Azumi67** [comment]
سلام. اکسترا فقط داخل سرور‌ های دیجیتال اوشن تست شده چون خودم دیجیتال اوشن دارم . مورد دیگر اینکه من به دلیل بیماری ، فعلا فعالیتی در گیت هاب نخواهم داشت .
