### ISSUE TITLE
ادیت کردن دستی پینگ سرویس ها

### ISSUE THREAD

**Issue by Kup1ng** [Azumi67/6TO4-GRE-IPIP-SIT#17]
سلام خسته نباشید
میشه لطف کنید همینجا یک اموزش کوچیک بهم بدید که برای ویرایش ایپی هایی که داخل پینگ سرویس ها قرار دادم چه فایل هایی را باید ادیت بکنم
اون فایلایی که هنگام انجام دستور مسیرشون را مینویسه را بررسی کردم ولی هیچکدوم چیزی تحت عنوان اون ایپی توش نیست
چون واقعا سخت هست که 10 تا سرور را هر دفعه قطع کنم و کلی ادم منتظر بمونن تا من تونل را تغییر بدم
مرسی بابت زحماتتون

**Comment by localroot4** [comment]
البته میتونی فایلهای زیر هم ادیت کنی برای مثال برای سرور 3 خارج میخوای داخل سرور ایران تغییر بدی:
nano /etc/private3.sh
nnao /etc/gre63.sh
