### ISSUE TITLE
مصرف 2 برابری ترافیک سرور ایران

### ISSUE THREAD

**Issue by MJKhani** [Azumi67/6TO4-GRE-IPIP-SIT#19]
با سلا و درود
و خسته نباشید
بسیار اسکریپت فوق العاده ای هست و کار راه انداز
فقط یک نکته ای که من چندین بار رو چندین سرور تست کردم و متوجه شدم که با روش ger6 مولتی سروری که استفاده میکنم به طور مثال ترافیک مصرفی من تقریبان 200 گیگه ولی در پنل کاربری سرور میبینم چیزی حوله هوش نزدیک به 400 مثلا 370 گیگ استفاده شده و اینو رو چندین سرور تست کردم و دقیقا از این موضوع مطمین هستم ایا دلیل خاصی داره چون با ایپی نیتیو 6 به این شکل نیست فقط در این روش مصرف ترافیک تقریبان دو برابر است.
و نکته دیگه در این روش ترافیک دانلود نیز دو برابر اپلود در پنل به پنل مصرف میشود!!!
در صورتی که با ایپی نیتیو ترافیک مصرفی دانلود و اپلود یکسان است!!!

**Comment by Azumi67** [comment]
سلام مرسی به خاطر نظر لطفتون . بله مصرف نهایی تا ۱.۴ بالاتر می‌ره .

**Comment by TiamaaShah** [comment]
مصرف همه مدل ها 1.4 مرن بالا یا ققط ger6 این طوری هستش؟

**Comment by Azumi67** [comment]
فکر کنم geneve اوکی باشه .‌با IPsec میتونید استفاده کنید
