### ISSUE TITLE
dns 

### ISSUE THREAD

**Issue by kalilovers** [Azumi67/6TO4-GRE-IPIP-SIT#2]
اگر امکانش هست یه اپشنی اضافه کنید بشه dns ست کرد رو کانفیگ های که اسکریپت میسازه مثلا eth0 رو تغییر میدیم تو netplan ست میشه رو کانفیگای اسکریپت نه 

تستی یه اکسترا نیتیو گرفتم اوکی بود تا اینکه dns رو از تو netplan برا نیتیو اصلی تغییر دادم . اکسترا از کار افتاد حتی بعد از اینکه dns قبلی رو گذاشتم کار نکرد

**Comment by kalilovers** [comment]
کانفیگ ها تو قسمت سرور ذخیره میشه بتونیم دستی dns یا mtu براشون تغییر بدیم 
با دستور netplan apply که کانفیگ رو ذخیره میکنه نیتیو اکسترا حذف میشه دوباره که گرفتم اوکی شد

**Comment by Azumi67** [comment]
سلام. اون به این دلیل هست که با روش دیگه اینکار انجام میشه . به صورت TEMPORARY به سرور اضافه میشه و با کرون ریست میشه . حالا برای حل اون مشکل پس از قرار دادن مولتی سرور ها ، فکر میکنم.

**Comment by kalilovers** [comment]
> سلام. اون به این دلیل هست که با روش دیگه اینکار انجام میشه . به صورت TEMPORARY به سرور اضافه میشه و با کرون ریست میشه . حالا برای حل اون مشکل پس از قرار دادن مولتی سرور ها ، فکر میکنم.

تشکر کامندش چیه به کرون جاب اضافه کنیم با ریستارت و.. نپره

**Comment by Azumi67** [comment]
به کرون که اضافه میشه . مشکل انجا هست که وقتی NETPLAN APPLY کنید ، ایپی اضافه میپره و تا ریبوت بعدی نمیاد . چون داخل کرون هست که پس از ریبوت اجرا کنه .
