### ISSUE TITLE
نصب نشدن روی یکی از سرورها

### ISSUE THREAD

**Issue by TiamaaShah** [Azumi67/6TO4-GRE-IPIP-SIT#20]
روی یکی از سرورها نصب نمیشه و بعد از انتخاب سرور این ارور رو میده
add tunnel "sit0" failed: No such device
Cannot find device "azumi2"

**Comment by Azumi67** [comment]
دقیقا خطای کامل رو بدید و توضیح بدید که چی میشه که چنین خطایی میاد . چون معمولا به خاطر بافر سایز به وجود میاد . تلاش کنید که یک بار کامل تمام کانفیگ هایی که با اسکریپت بر روی اون سرور انجام دادید رو به درستی uninstall کنید و بعد از ریبوت دوباره امتحان کنید .

**Comment by TiamaaShah** [comment]
My network interface name is venet0 
ممکن هست به خاطر اسم اینترفیس کارت شبکه باشه ؟

**Comment by Azumi67** [comment]
شما ببینید اصلا module sit داخل سرور شما لود شده یا نه. چون نتوانسته sit0 رو پیدا کنه . lsmod | grep sit
دستورات رو به صورت دستی هم وارد کنید تا ببینید دقیقا مشکل از کجا هست .
