### ISSUE TITLE
سوال

### ISSUE THREAD

**Issue by Saeedroshan1906** [Azumi67/6TO4-GRE-IPIP-SIT#21]
سلام به شما دوست عزیز یک موردی و این چند وقته برخورد داشتم خواستم نظرتونو بپرسم ، من انواع روش های اسکریپت رو پیاده سازی کردم و اکثریت هم کار میکنن اما یه موردی رو جدیدا در بعضی سرور های ایران داره واسم رخ میده اینه که مثلا بعد چند روز اون ایپی پرایوت سرور خارج در سرور ایران از کار میوفته و دیگه پینگ نمیده ، گاهی با عوض کردن روش مثلا ip6ip6 مجددا برقرار میشه بیشتر اوقات دیگه هر روشی بزنی اتصال برقرار نمیشه ، اما اگر سرور خارج و عوض کنی مجددا ارتباط برقرار میشه ، احساس میکنم توسط سرور ایران پکت ها شناسایی میشه به سرور مقصد .

**Comment by Azumi67** [comment]
سلام. چندین سناریو می‌تونه باشه. ممکنه سرور ایران شما تعدادی از سرورهای خارج رو در ساعات خاصی بر رویشان اختلال میندازه یعنی جز آی‌پی های کثیف و خاکستری هستند. امکانش هست که اصلا خود سرور ایران شما در ساعات مختلف اختلال داشته باشه و بله این امکان هم هست که روی روش هایی که انجام میدید اختلال میندازن. شما روش IPsec هم امتحان کنید و erspan و هم چنین ترکیب erspan icmp ولی دقت کنید که این روش ها رو باید هوشیارانه استفاده کرد و نباید تعداد زیادی یوزر بر روی آن قرار بدید یا سرور ایران دیگری تست کنید.

**Comment by mohamadaz** [comment]
بنظر شما پایدار ترین روش کدام هست؟
من icmp+ ipsec رو زدم و از ایپی تیبل برای فوروارد ترافیک استفاده کردم اما سر ساعت های مشخصی اختلال وجود داره و انگار شناسایی میشه

**Comment by Azumi67** [comment]
فکر نکنم به اون ربطی داشته باشه . بیشتر مورد شما به این شبیه هست که سرور ایران شما سر ساعات خاصی اختلال داره. روی icmp یوزر زیادی ندارید .
