### ISSUE TITLE
بهترین ترکیب

### ISSUE THREAD

**Issue by Mohammadaminsdr** [Azumi67/6TO4-GRE-IPIP-SIT#23]
سلام وقت بخیر ممنون بابت اسکریپت خفنتون خواستم بپرسم ازتون که کدوم از این روش ها پایدار تر و اتیبل تره ؟ و اینکه Geneve گزینه خوبیه ؟

**Comment by Azumi67** [comment]
سلام. همون geneve خوبه ولی داخل هر سرور ممکنه یک روش بهتر باشه.

**Comment by Mohammadaminsdr** [comment]
مصرف که تو این حالت دو برابر نیست ؟ اگه نباشه عالی میشه
