### ISSUE TITLE
cannot find device "azumi"

### ISSUE THREAD

**Issue by babakazizigithub** [Azumi67/6TO4-GRE-IPIP-SIT#24]
درود و احترام 
این اروری که ضمیمه کردم قابل حل هست؟ دلیلش چیه؟ 
فایروال خاموشه 
 رو یه سرور با دیتاسنتر یکسان اوکیه رو یکی دیگه این ارور رو دارم

ممنون

![photo_2024-05-17_19-34-26](https://github.com/Azumi67/6TO4-GRE-IPIP-SIT/assets/123808909/67eef57d-f3f2-4b67-a91e-0a0512df1265)

**Comment by Azumi67** [comment]
سلام کمی بهتر توضیح بدید . تک سرور کانفیگ میکنید ؟ چون ازومی بدون نامبر میبینم و به نظر اصلا اینترفیس ساخته نشده که بخواد mtu تنظیم بشه . دقیق بگید کدوم گزینه رو استفاده کردید . مورد دیگه اینکه صبر کنید امشب آپدیت بزرگی میدم، بعد از اون تست کنید .

**Comment by babakazizigithub** [comment]
ممنونم از پاسختون
بله single server هست
تانل Geneve  IPSEC IPV4 

روی یه سرور خارج و یه سرور ایران تست کردم اوکیه و کار میکنه
الان مجدد روی یه سرور خارج  و یه سرور ایران تست میکنم توی جفتش این ارور رو میده

دیتاستر خارجی هر دو سرور یکی
دیتاسنتر ایرانی هر دو سرور هم یکی
رنج آی پی ها هم یکی

ممنونم

**Comment by Azumi67** [comment]
خب این می‌تونه دو دلیل داشته باشه. فایروال یا اون سرور دوم اجازه geneve udp رو نمی‌ده که اگر ترکیبی نیست ، میتونید این محدودیت رو با geneve gre6 رد کنید .

**Comment by babakazizigithub** [comment]
نه هر دوتا سرور متناظر دقیقا عین هم هستند و از یک دیتاسنتر و هر دوتا با یه شرایط
هیچ فایروالی هم روشون نیست

**Comment by Azumi67** [comment]
بهتون گفتم . این مورد قبلا پیش اومده و اگر با ترکیبی، سرور ها بهم پینگ دادن،‌ یعنی همون موردی هست که من گفتم . به هر حال سرور در دست من نیست و فقط میتونم حدس بزنم .

**Comment by babakazizigithub** [comment]
درود و احترام
توی آپدیت جدیدتون هم تست کردم این مشکل حتی روی GRE هم هست
منتهی آی پی خارجی که تست کردم اوکی بود و اسکریپت ران میشد رنج 5.75 بود ولی روی سرورهایی که رنج 91.107 دارن میزنم همین ارور رو میده
چند تا 91 تست کردم رو همشون همین داستانه ولی تا رنج رو عوض میکنی حل میشه

**Comment by Azumi67** [comment]
مرسی که اطلاع دادید. بله بر روی بعضی رنج ها محدودیت هست و باید روش های دیگری رو تست کرد. مثلا icmp erspan
