### ISSUE TITLE
ipv6

### ISSUE THREAD

**Issue by Mohammadaminsdr** [Azumi67/6TO4-GRE-IPIP-SIT#25]
سلام وقت بخیر این تانل ها همشون ipv6 یکسان استفاده میکنن امکانش هست ویرایش کرد دستی ؟ یا مثلا خودش خودکار ipv6 از سایت بگیره بزاره اونجا ؟

**Comment by Azumi67** [comment]
سلام. ثابث بودن ایپی پرایوت مشکلی برای شما به وجود نمیاورد و تنها در سرور خود شما کارایی دارد.
