### ISSUE TITLE
6to4

### ISSUE THREAD

**Issue by pouriasharifzad** [Azumi67/6TO4-GRE-IPIP-SIT#26]
سلام روی سرور ایران بعد از آنینستال کردن آی پی های قبلی و ریبوت خواستم 6به4 10 خارج بزنم
3تا سرور اول درست کار میکنن اما سرور 4 به بعد کار نمیکنه
وقتی خواستم با کد زیر mtu مناسب رو پیدا کنم هم این ارور رو برای 4 به بعد میداد 
root@localhost:~# ping6 -c 4 -M do -s 1422 2002:841b::1
PING 2002:841b::1(2002:841b::1) 1422 data bytes
From 2002:801b::2 icmp_seq=1 Time exceeded: Hop limit
From 2002:801b::2 icmp_seq=2 Time exceeded: Hop limit
From 2002:801b::2 icmp_seq=3 Time exceeded: Hop limit
From 2002:801b::2 icmp_seq=4 Time exceeded: Hop limit

--- 2002:841b::1 ping statistics ---
4 packets transmitted, 0 received, +4 errors, 100% packet loss, time 3036ms

و روی سرور ایران هم آی پی 6 هایی که اختصاص میداد بعد از سرور 3 دیگه به ترتیب نبود یعنی از 2002:821b::2 یهو میپره روی 2002:861b::2

**Comment by Azumi67** [comment]
سلام مرسی اطلاع دادید. چون ساختار کلی عوض شده بود و محاسبه mtu به صورت اتومات هم دست زدم، کمی مشکل ساز شده بود. الان باید کار کنه.

**Comment by pouriasharifzad** [comment]
ممنون از وقتی که میزارین و کارتون عالیه
یعنی دیگه نیاز نیست mtu دستی بدیم؟

**Comment by pouriasharifzad** [comment]
ممنون و کارتون عالیه
الان 6 تا سرور ست کردم
وقتی که تو دکودمو وارد میکنم آی پی لوکال رو سی پی یو و رم 100 میشه و سرور هنگ میکنه
