### ISSUE TITLE
feature request 

### ISSUE THREAD

**Issue by Kup1ng** [Azumi67/6TO4-GRE-IPIP-SIT#27]
سلام خسته نباشید
اول مرسی از آپدیت اخیرتون که شروعی دوباره به این اسکریپت کاربردی بود
دوم هم یک درخواست داشتم برای آپدیت های بعدی که امکان ویرایش تانل در حالت multiple  و single  برای ۳ تونل پر استفاده این روز ها اضافه بشه
ip6ip6 - gre6 - 6to4 any cast
با تشکر از شما

**Comment by Azumi67** [comment]
سلام مرسی. میتونید بیشتر توضیح بدید ؟ چون الان ویرایش سرور‌ رو اضافه کردم و میشه هر سرور‌ رو جداگانه پاک و اضافه کرد.

**Comment by Kup1ng** [comment]
اونطور که داخل گیت هابتون مشاهده کردم ظاهرا فقط ویرایش را جهت تانل 6to4 و 6to4 ipsec  فراهم کردید 
اما الان که اسکریپت را توی سرور زدم دیدم برای همه تانل ها اومده و بسیار عالی شده 
ببخشید که وقتتونم گرفتم و باز هم تشکر میکنم از این همه ویژگی خوب
اگر یک کانال تلگرامی یا گروهی چیزی هم بزنید که بتونیم از آپدیت ها و تغییرات زودتر مطلع بشیم و مشکلاتمونو با دوستان حل بکنیم بسیار عالی میشه 
روز خوش
