### ISSUE TITLE
multiple 6to4 CPU

### ISSUE THREAD

**Issue by pouriasharifzad** [Azumi67/6TO4-GRE-IPIP-SIT#28]
ممنون از وقتی که میزارین و کارتون عالیه
الان 6 تا سرور ست کردم
وقتی که تو دکودمو وارد میکنم آی پی لوکال رو سی پی یو و رم 100 میشه و سرور هنگ میکنه

**Comment by Azumi67** [comment]
من خودم شخصا نمیتونم این مورد رو تست کنم چون نیازم نمیشه . بررسی کنید که چی باعث میشه که اینطوری‌ شده . مانیتورینگ کنید . اگر تعداد زیاده ،‌میخواهید با تعداد کمتر تست کنید و ببینید باز هم اینطوری میشه یا نه . میتونید از داخل ویرایش سرور یک سرور رو کم کنید. باید هم در خارج و هم در ایران حذف بشه .

**Comment by pouriasharifzad** [comment]
اشتباه از خودم بود ممنونم
