### ISSUE TITLE
Opiran Script

### ISSUE THREAD

**Issue by AliHemmati79** [Azumi67/6TO4-GRE-IPIP-SIT#3]
سلام خسته نباشید
در مورد  Opiran Script میشه توضیح بدین که دقیقا چه کاری روی سرورها انجام میده؟ و اینکه استفاده کنیم یا نکنیم چقدر تاثیر داره؟

**Comment by Eslender73** [comment]
> سلام . bbrv3 و بهینه کردن سرور شما از کارهای optimizer هست. بر روی همه سرور هاتون نصب کنید. تنظیم dns time zone و ip forward و غیره

استاد بهترین روش برای دایرکت تانل ip6 کدوم روشتونو پیشنهاد میکنید؟
من از frp kcp شما دارم استفاده میکنم معرکست سرعت فوقعلاده
همین روش مستقیمشم هست؟

**Comment by Azumi67** [comment]
چند تا دایرکت قرار دادم . برای frp هم اپدیت quic برای v2ray و وایرگارد هم اماده کردم. بعدا اضافه میکنم. میمونه tls

**Comment by AliHemmati79** [comment]
> سلام . bbrv3 و بهینه کردن سرور شما از کارهای optimizer هست. بر روی همه سرور هاتون نصب کنید. تنظیم dns time zone و ip forward و غیره

ممنون

**Comment by AliHemmati79** [comment]
الان بهترین روش تانل کدوم یکی هست که سرور ایران فیلتر نشه؟
1سرور خارج و 2 سرور ایران دارم
از روش لود بالانسر frp استفاده میکنم چند روز پیش یکی از سرورهای داخلی ایران اکسس شد.

**Comment by Azumi67** [comment]
> الان بهترین روش تانل کدوم یکی هست که سرور ایران فیلتر نشه؟ 1سرور خارج و 2 سرور ایران دارم از روش لود بالانسر frp استفاده میکنم چند روز پیش یکی از سرورهای داخلی ایران اکسس شد.

چه نوع کانفیگی استفاده کردید ؟ چقدر یوزر داشتید ؟ چه دیتاسنتری ؟

**Comment by AliHemmati79** [comment]
> > الان بهترین روش تانل کدوم یکی هست که سرور ایران فیلتر نشه؟ 1سرور خارج و 2 سرور ایران دارم از روش لود بالانسر frp استفاده میکنم چند روز پیش یکی از سرورهای داخلی ایران اکسس شد.
> 
> چه نوع کانفیگی استفاده کردید ؟ چقدر یوزر داشتید ؟ چه دیتاسنتری ؟

اکثرا کانفیگ ها vless-tcp-tls
یوزر درحد 500 تا 
دیتاسنتر لایزر
44 تا اینباند دارم که 4 تاش از نوع ws هستن ولی تعداد یوزرشون کمه

**Comment by Azumi67** [comment]
> > > الان بهترین روش تانل کدوم یکی هست که سرور ایران فیلتر نشه؟ 1سرور خارج و 2 سرور ایران دارم از روش لود بالانسر frp استفاده میکنم چند روز پیش یکی از سرورهای داخلی ایران اکسس شد.
> > 
> > 
> > چه نوع کانفیگی استفاده کردید ؟ چقدر یوزر داشتید ؟ چه دیتاسنتری ؟
> 
> اکثرا کانفیگ ها vless-tcp-tls یوزر درحد 500 تا دیتاسنتر لایزر 44 تا اینباند دارم که 4 تاش از نوع ws هستن ولی تعداد یوزرشون کمه

من اسکرین شات هایی دیدم که میگن ws استفاده نکنید و لایزر هم که خیلی ها رو access کرده. فعلا من بر روی لایزر access نشدم.  پس تلاش کنید از همون tcp استفاده کنید و ببنید چی میشه.

**Comment by AliHemmati79** [comment]
> > > > الان بهترین روش تانل کدوم یکی هست که سرور ایران فیلتر نشه؟ 1سرور خارج و 2 سرور ایران دارم از روش لود بالانسر frp استفاده میکنم چند روز پیش یکی از سرورهای داخلی ایران اکسس شد.
> > > 
> > > 
> > > چه نوع کانفیگی استفاده کردید ؟ چقدر یوزر داشتید ؟ چه دیتاسنتری ؟
> > 
> > 
> > اکثرا کانفیگ ها vless-tcp-tls یوزر درحد 500 تا دیتاسنتر لایزر 44 تا اینباند دارم که 4 تاش از نوع ws هستن ولی تعداد یوزرشون کمه
> 
> من اسکرین شات هایی دیدم که میگن ws استفاده نکنید و لایزر هم که خیلی ها رو access کرده. فعلا من بر روی لایزر access نشدم. پس تلاش کنید از همون tcp استفاده کنید و ببنید چی میشه.

بله درسته منم چندجایی دیدم که گفتن ws مناسب نیست، برای همین همه‌رو انتقال میدم به tcp.🙏🏻
