### ISSUE TITLE
از بین رفتن تانل و ای پی لوکال 

### ISSUE THREAD

**Issue by SasanKHZN** [Azumi67/6TO4-GRE-IPIP-SIT#31]
سلام و خدا قوت
ممنون بابت تمام زحماتت
چرا بعد از ریست سرور ای پی لوکا و تانل از بین می رود امکان اصلاحش هست

**Comment by Azumi67** [comment]
سلام. مرسی. نه نباید چنین اتفاقی بیوفتد و این بارها تست شده و درست کار میکنه. باید کرون جاب خود را بررسی کنید و ببینید دقیقا مشکل از کجا هست که دستورات اجرا نمیشود.
