### ISSUE TITLE
نصب بر روی centos

### ISSUE THREAD

**Issue by AerEbi** [Azumi67/6TO4-GRE-IPIP-SIT#32]
مرسی بابت اسکریپتی که گذاشتی و تند تند آپدیت می‌کنی.

چطوری میشه بین دوتا سرور که یکیش centos هست اسکریپت رو اجرا کرد؟
من دستی تا جایی که میشد اوبونتو رو به centos تغییر دادم ولی باز خطا می‌گیرم.

ممنون می‌شم راهنمایی کنی🙏

**Comment by Azumi67** [comment]
سلام مرسی. نه من دستورات را بر اساس os های دبیان و اوبونتو نوشتم .

**Comment by AerEbi** [comment]
روش یا اسکریپتی پیشنهاد می‌دی که روی centos جواب بده؟

**Comment by Azumi67** [comment]
شما دستورات رو از داخل یکی از روش ها بگیرید و برای os خودتون یک اسکریپت ساده درست کنید.
