### ISSUE TITLE
GRE

### ISSUE THREAD

**Issue by mehdikhaksar66** [Azumi67/6TO4-GRE-IPIP-SIT#34]
سلام خسته نباشید چرا دستور GRE میزنم آی پی میگیرم اوکی میشه ولی بعد یه روز اینا وصل نمیشم دیگه به اون آی پی دوباره دستور GRE میزنم آی پی میگیرم وصل میشم

**Comment by Azumi67** [comment]
سلام. کمی بهتر توضیح دهید. کدام گزینه رو انتخاب کردید ؟مطمئن نیستم اما شما به نظر میاد که سرور ایرانتان در ساعات خاصی ارتباط شما رو با اون روش خاص قطع می‌کنه و دوباره برمی گردونه . شما باید روش های دیگری رو تست کنید .
