### ISSUE TITLE
مشکل در نصب ، خطای پایتون 

### ISSUE THREAD

**Issue by mr-bz** [Azumi67/6TO4-GRE-IPIP-SIT#35]
در اجرای اسکریپت 
python3 <(curl -Ls https://raw.githubusercontent.com/Azumi67/6TO4-GRE-IPIP-SIT/main/ipipv2.py --ipv4)

این خطارو دارم 
/dev/fd/63:73: SyntaxWarning: invalid escape sequence '\_'
SyntaxError: Non-UTF-8 code starting with '\xe2' in file /dev/fd/63 on line 96,
but no encoding declared; see https://peps.python.org/pep-0263/ for details

 python3 -V
Python 3.12.3

**Comment by Azumi67** [comment]
برای من کار می‌کنه با این حال یک خط کد مربوط به utf8 اولش اضافه کردم .اگر برای شما کار نکرد یا به دیفالت encoding پایتون شما در آن سرور‌ بر میگردد یا configuration . باید آن موارد را بررسی کنید .

**Comment by mr-bz** [comment]
بله حالا شد این خطا ، 
/dev/fd/63:73: SyntaxWarning: invalid escape sequence '\_'
/dev/fd/63:85: SyntaxWarning: invalid escape sequence '\ '
  File "/dev/fd/63", line 140
    left=%defaultroute
                    ^^^
SyntaxError: (unicode error) 'utf-8' codec can't decode bytes in position 168-169: unexpected end of data


ورژن اوبونتو ۲۴ هست مشکلی نداره با این ورژن؟

**Comment by Azumi67** [comment]
من روی اون ورژن تست نکردم . من از دبیان 12 استفاده میکنم .

**Comment by Hamed-F** [comment]
> در اجرای اسکریپت python3 <(curl -Ls https://raw.githubusercontent.com/Azumi67/6TO4-GRE-IPIP-SIT/main/ipipv2.py --ipv4)
> 
> این خطارو دارم /dev/fd/63:73: SyntaxWarning: invalid escape sequence '_' SyntaxError: Non-UTF-8 code starting with '\xe2' in file /dev/fd/63 on line 96, but no encoding declared; see https://peps.python.org/pep-0263/ for details
> 
> python3 -V Python 3.12.3

روی اوبونتو ۲۴ این مشکل هست 
اوبونتو ۲۲ نصب کن اکی میشه

**Comment by mr-bz** [comment]
تشکر ازشما

**Comment by jadopcb** [comment]
سلام
تست کردم و استفاده  
عالی بود
به خصوص {اپدیت 5 سرور ایران و 10 سرور خارج با آموزش قرار داده شد}

تشکر
خسته نباشید 

ابونتو 22.4 نصب کردم

**Comment by Azumi67** [comment]
بسیار عالی . حالا بعدا وقت کنم روی اوبونتو 24 هم نگاه میکنم.

**Comment by Azumi67** [comment]
> تشکر ازشما

لطفا برای ubuntu24 با این دستور هم تست بفرمایید

```
bash -c "$(curl -fsSL https://raw.githubusercontent.com/Azumi67/6TO4-GRE-IPIP-SIT/main/ubuntu24.sh)"
```
