### ISSUE TITLE
mtu

### ISSUE THREAD

**Issue by alphamanrays** [Azumi67/6TO4-GRE-IPIP-SIT#36]
با سلام و خسته نباشید خدمت شما 
اگر هنگام 6-4 مقدار ام تی یو وارد نکنیم دیفالت وارد میکنه یا نه و اینکه بعدا چطور میتونیم ام تی یو رو عوض کنیم ؟

**Comment by Azumi67** [comment]
سلام. برای بیشتر سرور به صورت پیش فرض انتخاب میشه اما برای بعضی از سرور ها که انجام نمیشد محاسبه اتومات وجود داشت که الان برداشته شده و باید از طریق گزینه edit mtu و گزینه مربوطه، مقدار مناسب را قرار دهید . برای تک سرور و مولتی سرور به صورت جداگانه edit mtu قرار داده شده .

**Comment by alphamanrays** [comment]
خیلی ممنون از زحمات شما
