### ISSUE TITLE
مشکل از کار افتادن تانل بعد مدتی

### ISSUE THREAD

**Issue by Ten10vpn** [Azumi67/6TO4-GRE-IPIP-SIT#38]
با چندین مدل از جمله sit, 6to4 , gre6 تانل انجام دادم.
اولش دزست کار میکنه.
بعد یه روز بعضئ سرورها از کار میافته.
سرور ایران و خارج به هم پینگ نمیدهند.
حتی ادیت سرور هم میزنم ولی باز هم ارتباط برقرار نمیشه

**Comment by Azumi67** [comment]
سلام. ممکنه چندین دلیل داشته باشه. یک اختلال و لیمیت شدن ان روش در سرور ایران شما و ان سرور خارج مشخص. معمولا با عوض کردن سرور ایران یا خارج های متعدد، این مشکل حل میشه . ممکنه ایپی شما جز ایپی های خاکستری باشه و یا کثیف و باعث اختلال شما میشه. شما بهتره روش های دیگه هم تست کنید یا سرور هاتون رو بررسی کنید. icmp یا erspan یا geneve ترکیبی هم تست کنید. هم چنین چندین روش ipsec هم تست کنید.
مورد دیگر اینکه اگر سرور شما ریست شده و تانل از کار افتاده حتما بررسی نمایید که اگر اسکریپت دیگری استفاده کردید، دستورات کرون من پاک نشده باشد که باعث از کار افتادن تانل میشه. پس بهتره ازش یک بک آپ داشته باشد
چند مورد از دلایل از کار افتادن تانل را خدمت شما عرض کردم.

**Comment by Ten10vpn** [comment]
سلام . اصلا انتظار نداشتم جوابمو بدین. بسیار منتونم.
من ۶ سرور خارج رو با دو سرور ایران تانل کردم.به روش sit
دو سرور خارجم بعد یه روز از کار افتاد. در واقع یکیشون ارتباطش با هر دو
ایران قطع شد و یکیش فقط با یک ایران.

حالا جالب اینجاست وقتی میرم سرورهای حارج رو ریبیلد میکنم و مجدد تانل میکنم
درست میشن

**Comment by Azumi67** [comment]
خب پس از روش جدیدی که قرار دادم استفاده کردید .میشه بگید اون دو سرور خارجی که بعد از یک مدت مشکل دار شدن کدام گزینه ها بودند ؟ یعنی چه سرور خارجی بودند ؟ (که کدهای مربوط به اون سرور ها رو دوباره نگاه کنم)
مورد دیگر اینکه حتی ریبوت هم کنید باز هم پینگ نمیدن ؟
یک مورد دیگر هم که هست اینه که ممکنه موقعی که rebuild کردید، ان موقع اختلالی نبوده اخه باید توجه داشته باشید که چند روزه ایپی های 4 سرور ایران قطع و وصل میشه و این مورد به وضوع در kuma مشاهده میشه و وقتی ایپی 4 قطع بشه طبیعتا تانل شما هم در ان برهه زمانی از کار خواهد افتاد.

**Comment by Ten10vpn** [comment]
سرور خارج ۱ و ۳
قابل توجه اینکه سرور خارج سه ای پی کاملا فیلتر هست ولی با این حال دیشب ارتباط برقرار شد و به هم پینگ دادند.
سرور خارج ۱ سالمه ، البته شاید محدود باشه ولی توی چک هاست چیزی نشون نمیداد.
با دو ایران ۱ (افرانت) و ایران ۲ (آسیاتک ) تانل کرده بودم به همراه چند سرور خارج دیگر.
صبح جفت خارج ها روی هر دو ایران از کار افتاد.
سرورها رو ریبوت کردم و مجدد ادیت سرور زدم و تانل انجام دادم.
سرور ایران یک با خارج یک اوکی شد ولی با ایران ۲ نه.
سرور خارج ۳ که کلا ای پی فیلتر بود با هیچکدام اوکی نشد.
سرور ریبولد کنم مشکل حل میشه . نمیدونم چرا.

در کل بسیار ممنونم از رشهای جذابی که میزارین.

مخصوصا تانل ریورس ws که بسیار عالی و بدون اختلال هستش

**Comment by Azumi67** [comment]
بسیار عالی. من همین سرور خارج یک و 3 را با دو ایران تانل میکنم و به مدت دو روز بررسی میکنم. اگر مشکلی باشد باید برای من هم نشان داده شود. چیزهایی که گفتید میتونه به دلیل چندین مورد باشه اما باید خودم تست کنم و ببینم چنین موضوعی برای من هم پیش بیاد یا خیر. مورد دیگر اینکه برای سرور های فیلتر اگر بتونیم از ایپی نیتیو و یا bridge یا encapsulation اضافی برای ارتباط استفاده کنیم هم خوب هست اما بیشتر مشکلات بیشتر به خاطر سرور های ایران میباشد. happy hunting

**Comment by Azumi67** [comment]
مورد دیگه اینکه من فکر میکنم در اینده بیشتر چنین مورد هایی میبینیم . برای همین باید به همین ده سرور خارج و 5 سرور ایران روش های دیگر هم اضافه شود که در صورت نیاز به اون سوییچ کنید . چون تنها راه دور زدن محدودیت در حال حاضر سوییچ کردن و استفاده از روش های دیگر هست که نیازمند به این میباشد که من روش های دیگر هم به ده سرور خارج و 5 سرور ایران هم اضافه کنم.

**Comment by Ten10vpn** [comment]
بسیار عالی. در هر صورت از پاسخگویی شما بسیار منونم. و من همیشه پیج شما رو برای روشهای جدید تر دنبال میکنم

**Comment by Azumi67** [comment]
سلام . من از دیروز تا الان سه سرور خارج که همشون برای اوشن بودن رو به لایزر و اروان تانل کردم و تا آلان مشکلی نداشته . شما همون اختلال سرور داشتید . راه حلشم اینه که روش‌های مختلفی برای سرور ایران و چند خارج قرار بگیره ، که در صورت نیاز سوییچ بشه که اگر یک یا دو سرور ایران از کار افتاد، بقیه کار بکنند .

**Comment by Ten10vpn** [comment]
بشیار ممنونم از پیگیری عالی و توسعه پیجتون
