### ISSUE TITLE
Config Ping

### ISSUE THREAD

**Issue by DontJer** [Azumi67/6TO4-GRE-IPIP-SIT#39]
سلام روز بخیر
من یه مشکلی که تازگی باهاش روبرو شدم اینه کانفیگی که با 6to4 میزنم داخل برنامه v2raynG پینگ بهم نمیده یا پینگای خیلی بالا میده ولی داخل اسپیدتست پینگ 120 130 میگیرم و هیچ مشکلی بابت سرعت ندارم تانل هم از ‌Rathole استفاده میکنم
این نکته رو هم بگم که همون مدل کانفیگ با ورژن ۶ نیتیو مشکلی از این بابت نداره داخل لاگ برنامه هم ارور هندشیک با gstatic میگیرم البته با cp.cloudflare هم همینه 
هدر هم گذاشتم تفاوتی ایجاد نکرد
ممکنه راهنمایی کنید؟

**Comment by Azumi67** [comment]
سلام. الان چندین روزه روش های لوکال مثل sit و اینها مثل اینکه اختلالاتی رو به خاطر مشکلات ایپی 4 تجربه میکنند، یک دلیلش این میتونه باشه . اگر میخواهید پینگ هندشیک رو پایین تر بیارید میتونید سرورتون اوپتیمایز کنید مثل fast open و اینها یا داخل hosts ایپی ها کلودفلر رو بذارید . اگر در اینده sit یا روشی محدود و لیمیت شد، لطفا ان روش را هم عوض کنید.
