### ISSUE TITLE
مشکل از کار افتادن تانل بعد از یک روز 

### ISSUE THREAD

**Issue by mohsenksk** [Azumi67/6TO4-GRE-IPIP-SIT#40]
سلام و وقت به خیر خدمت شما... ممنونم بابت اسکریپت فوق العاده خوبتون ...
من وقتی تانل برقرار میکنم بین ۱سرور ایران و ۱سرور خارج با روش ip6ip6 متاسفانه بعد از گذشت حدود ۲۰ساعت اون ip6 لوکال هر سرور نه از داخل ایران و نه خارج به هم پینگ نمیدن و انگار تانل از کار میافته ولی به طور کلی جفت سرور سالمه و این که بهم با ipv4 اصلیشون به هم پینگ میدن...
مشکل رو چی جور میتونم حل کنم که تانل از کار نیافته؟

**Comment by Azumi67** [comment]
سلام ‌ اینو در issue قبلی جواب دادم . به سرور ایران مربوطه و روش دیگری رو تست کنید که در اون سرور‌ ایران کار می‌کنه . یک Kuma هم نصب کنید تا بهتر بتوانید قطعی های سرورتون رو ببینید و بررسی کنید .
