### ISSUE TITLE
question 

### ISSUE THREAD

**Issue by Kup1ng** [Azumi67/6TO4-GRE-IPIP-SIT#41]
سلام خسته نباشید
میخواستم ببینم شما کدوم یکی از روش های اسکریپت را پیشنهاد میکنید که سرور خارج روی سرور ایران محدود نشه ( یا دیرتر بشه ) و پینگش قطع نشه ؟

**Comment by Azumi67** [comment]
سلام فعلا من از geneve ipsec با پورت فوروارد استفاده میکنم که مشکلی ندارم. اما به زودی vxlan با encapsulation vni 123 توسط سه روش با بریج و بدون بریج و با پورت udp سورس و destination به صورت تک سرور بیرون میدم که اونم فکر میکنم خیلی خوب باشه. مخصوصا ترکیباتش با dns و سایر موارد مثل geneve.

**Comment by Kup1ng** [comment]
تشکر از شما
