### ISSUE TITLE
گیر کردن

### ISSUE THREAD

**Issue by Mohammadaminsdr** [Azumi67/6TO4-GRE-IPIP-SIT#42]
سلام وقت بخیر ما اسکریپت رو ران میکنیم ولی ران نمیشه مرجله اخر خواستم ببینم مشکل از چی میتونه باشه 
![Screenshot 2024-06-07 145201](https://github.com/Azumi67/6TO4-GRE-IPIP-SIT/assets/141396498/7c13336b-f79f-442d-bbad-ac055262a78e)

**Comment by Azumi67** [comment]
سلام .شما میتونید پیش نیاز ها رو نصب کنید و سپس با دستور پایتون،  تنها اسکریپت را اجرا نمایید.

**Comment by Mohammadaminsdr** [comment]
Command 'python' not found, did you mean:
  command 'python3' from deb python3
  command 'python' from deb python-is-python3
  
  این ارور رو میده

**Comment by Azumi67** [comment]
ببینید شما اول پیش نیاز ها مثل colorama و netifaces رو نصب کنید با دستوراتی که قرار دادم و بعد با python3 اجرا کنید . دستورات رو از داخل گیت هاب به ترتیب اجرا کنید .

**Comment by Mohammadaminsdr** [comment]
sudo apt-get install python-pip -y  &&  apt-get install python3 -y && alias python=python3 && python -m pip install colorama && python -m pip install netifaces

python3 <(curl -Ls https://raw.githubusercontent.com/Azumi67/6TO4-GRE-IPIP-SIT/main/ipipv2.py --ipv4)

به این ترتیب میزنیم ارور میده

**Comment by Azumi67** [comment]
از اینها هم استفاده کنید 
apt install python3 -y && sudo apt install python3-pip &&  pip install colorama && pip install netifaces && apt install curl -y && python3 <(curl -Ls https://raw.githubusercontent.com/Azumi67/6TO4-GRE-IPIP-SIT/main/ipipv2.py --ipv4)
 و بعد 
python3 <(curl -Ls https://raw.githubusercontent.com/Azumi67/6TO4-GRE-IPIP-SIT/main/ipipv2.py --ipv4)
 یا اینم تست کنید 
bash -c "$(curl -fsSL https://raw.githubusercontent.com/Azumi67/6TO4-GRE-IPIP-SIT/main/ubuntu24.sh)"

در صورت پایداری مشکل، از ai برای حل مشکلتون استفاده نمایید .

**Comment by MooeinT** [comment]
سلام
منم همین مشکل رو دارم و از دیشب تا الات نتونستم اسکریپت نصب کنم
دیشب ی بار شد دیگه نشد
hosts عوض کردم
nameserver عوض کردم
dns عوض کردم
متاسفانه راهی نداشت

**Comment by MooeinT** [comment]
root@78:~# python3 <(curl -Ls https://raw.githubusercontent.com/Azumi67/6TO4-GRE-SIT/main/ipipv2.py --ipv4)
  File "/dev/fd/63", line 1
    404: Not Found
             ^
SyntaxError: invalid syntax

**Comment by Azumi67** [comment]
سلام. مشکل شما به دلیل تغییر لینک شما است . از این استفاده کنید
 python3 <(curl -Ls https://raw.githubusercontent.com/Azumi67/6TO4-GRE-IPIP-SIT/main/ipipv2.py --ipv4)

**Comment by MooeinT** [comment]
ممنونم ازت
من دوتا سرور خارج رو میحوام به یک سرور ایران وصل کنم
یکیش وصل میشه اون یکی پینگ نمیده نمیدونم چرا ؟
به این ربط داره که یه سرورم tls ws هستش یا نه ؟

**Comment by Azumi67** [comment]
نه فکر نکنم ربطی داشته باشه . روش های دیگه تست کنید . سرورتون ممکنه جز سرور های اختلال دار باشه.

**Comment by MooeinT** [comment]
و اینکه فقط یک بار اجرا میشه این لینکی ک فرستادین
و باید دوباره برای اجرا ریبیلد کنم سرورو
انگار یهو میمیره کلا

**Comment by MooeinT** [comment]
روش پیشنهادی خودتون کدومه برای دو سرور خارج و 1 ایران

**Comment by Azumi67** [comment]
> و اینکه فقط یک بار اجرا میشه این لینکی ک فرستادین و باید دوباره برای اجرا ریبیلد کنم سرورو انگار یهو میمیره کلا

من چنین مشکلی ندارم . شاید زیادی سرورتون رو تغییر دادید . سعی کنید زیاد سیستم عاملتون رو دست نزنید .

**Comment by Azumi67** [comment]
> روش پیشنهادی خودتون کدومه برای دو سرور خارج و 1 ایران

من خودم مدتی هست که از geneve و IPsec و پورت فوروارد استفاده میکنم . امروز بعد از امتحان شاید vxlan هم اضافه کنم که میتونید تست کنید .

**Comment by MooeinT** [comment]
ممنون از شما بابت تمامی زحماتی که برای ما و این وضع اینترنت میکشید با این همه مشکلی که خودتون درگیرش هستین
انشالله هرجا که هستین موفق و موُِید باشید و تنتون سالم باشه

**Comment by Azumi67** [comment]
مورد دیگری که هست اینه که چون حجم فایل بالا هست و اسکریپت حجیم شده، شما میتونید خود release file رو اجرا کنید . مثلا این دستور شاید بهتون کمک کنه 

bash -c "$(curl -fsSL https://raw.githubusercontent.com/Azumi67/6TO4-GRE-IPIP-SIT/main/ubuntu24.sh)"

**Comment by Azumi67** [comment]
> ممنون از شما بابت تمامی زحماتی که برای ما و این وضع اینترنت میکشید با این همه مشکلی که خودتون درگیرش هستین انشالله هرجا که هستین موفق و موُِید باشید و تنتون سالم باشه

مرسی. شما‌ هم همینطور

**Comment by MooeinT** [comment]
متاسفانه ورژن ubuntu 22 هستش برای من

**Comment by Azumi67** [comment]
> متاسفانه ورژن ubuntu 22 هستش برای من

اونم تست کنید فکر کنم جواب میده . بعد بهم اطلاع بدید

**Comment by MooeinT** [comment]
امتحاناتون رو مطمئن باشید که با بالاترین نمره و درجه پاس میکنید قطعا
چون دعای خیر خیلیها پشت سرتون هستش
تنها راه ارتباطی با شما همینه ؟

**Comment by Azumi67** [comment]
> امتحاناتون رو مطمئن باشید که با بالاترین نمره و درجه پاس میکنید قطعا چون دعای خیر خیلیها پشت سرتون هستش تنها راه ارتباطی با شما همینه ؟

پس از امتحان ها دوباره به گروه اپیران برمی‌گردم . غیر از اون بله در گیت هاب هستم .

**Comment by MooeinT** [comment]
اگه میدونستم انقدر کارگشا هستین زودتر پیام میدادم خدمتتون 
از ساعت 2 بامداد درگیر این موضوع هستم که خداروشکر با این ریلیز اخر مشکلم حل شد و الان میخوام geneve رو امتحان کنم

**Comment by MooeinT** [comment]
متاسفانه نه geneve و نه sit جواب ندادن

**Comment by MooeinT** [comment]
از کدوم اسکریپت برای port forward استفاده کنم ؟

**Comment by Azumi67** [comment]
> متاسفانه نه geneve و نه sit جواب ندادن

شما ممکنه سرورتون مشکل دیگری داشته باشه.

**Comment by Azumi67** [comment]
> از کدوم اسکریپت برای port forward استفاده کنم ؟

شما از همون dokodemo استفاده کنید . من ممکنه نتونم دیگر جواب بدم .

**Comment by MooeinT** [comment]
دکو دیگه جواب نمیده برام حدودا 1هفته هستش از کار افتاده .. 6to4 جواب میده اما روی تک سرور 
روی مولتی جواب نمیده نمیدونم چرا
هرموفع تونستین بفرمایید کامل توضیح بدم بفرمایید مشکل از کجاس

**Comment by MooeinT** [comment]
راستی چطور میشه این کرون جاب ها رو از روی سرور حذف کرد به صورت دستی ؟
برای مواقعی مثل موقعیت من که یهو سرورای ایران به مشکل میخوره و کانکت نمیشه به گیت هاب

**Comment by Azumi67** [comment]
> دکو دیگه جواب نمیده برام حدودا 1هفته هستش از کار افتاده .. 6to4 جواب میده اما روی تک سرور روی مولتی جواب نمیده نمیدونم چرا هرموفع تونستین بفرمایید کامل توضیح بدم بفرمایید مشکل از کجاس

من dokodemo استفاده نمیکنم اما به نظر میاد سرور ایرانتان اختلال دارد .  اگر مولتی جواب نمی‌ده دلیلش اینه که اون سرور خارج دوم در سرور ایران شما مشکل دار می‌باشد . باید مثلا چندین سرور ایران داشته باشید که با سرور های متفاوت خارج اگر سرور‌ اولی کار‌ نکرد ،‌سرور دوم ایران کار کند.
برای حذف کرون جاب هم با این دستور crontab -e واردش میشوید و سپس دستور مربوطه را پاک میکنید .

**Comment by omidmehdizadeh2** [comment]
سلام دوست عزیز 
ممنونم بابت کدهایی که زحمت کشیدید. 
چند تا سوال داشتم از شما
- اگر سرور ایران اوبونتو باشه و سرور خارج سنت او اس باشه ، مشکلی نداره ؟
- بعد از ری استارت تانل ها تا پاک میشه ؟
- آیا در آینده ویدئو آموزشی هم میزارید ؟

**Comment by Azumi67** [comment]
> سلام دوست عزیز ممنونم بابت کدهایی که زحمت کشیدید. چند تا سوال داشتم از شما
> 
> * اگر سرور ایران اوبونتو باشه و سرور خارج سنت او اس باشه ، مشکلی نداره ؟
> * بعد از ری استارت تانل ها تا پاک میشه ؟
> * آیا در آینده ویدئو آموزشی هم میزارید ؟

سلام. من یوتیوب ندارم و تنها آموزش نوشتاری می‌نویسم . اگر اسکریپت دیگری استفاده‌ کردید و دستورات کرون پاک شود ، بله تانل پس از ریبوت حذف میشود . اگر دستورات کرون باقی بماند، طبیعتاً تانل هم پس از ریبوت برقرار خواهد بود . همیشه از کرون یک بک آپ داشته باشید .من تنها بر روی اوبونتو و دبیان تست کردم .
