### ISSUE TITLE
حذف ip local

### ISSUE THREAD

**Issue by Mehranhich** [Azumi67/6TO4-GRE-IPIP-SIT#43]
سلام خسته نباشید میخوام کل تانل و ای پی لوکال های ک ساخته شده رو ب صورت یکجا بزنم حذف کنم چیکار کنم ئستور خاصی هست؟چون وقتی تکی uninstall میکنم و ریبوت هم میکنم باز ip local وجود داره و حذف نمیشه همیشه این مشکل رو دارم من

**Comment by Azumi67** [comment]
سلام . شما آی‌پی اشتباه رو پاک میکنید . اول برید داخل tunnel names و نام اینترفیس رو ببینید . مثلا اگر azumi و azumip دارید ، باید ipip رو پاک کنید . بقیه هم به همین صورت هست . اگر باز هم نتوانستید، از داخل crontab -e دستورات مربوط به لوکال رو پاک کنید .

**Comment by Mehranhich** [comment]
![Capture](https://github.com/Azumi67/6TO4-GRE-IPIP-SIT/assets/119574380/7a792165-cc9e-482c-a00e-26580624271f)
ممنون بابت پاسخ
الان این کدومه من کدومو باید uninstall کنم؟
اگر باز هم نتوانستید، از داخل crontab -e دستورات مربوط به لوکال رو پاک کنید .
این بخش دوم هم خوب متوحه نشدم وقتی دستورشو زدم ممنون میشم دقیقتر توضیح بدین

**Comment by Azumi67** [comment]
این یک راهنما هست . شما این رو به خاطر بسپارید . بعد دستور ip a رو میزنید . نام اینترفیس ها رو ببینید . داخلشون ببینید کدوم یکی از اینها هست . اینطوری میتونید به درستی پاک کنید .
روش دوم هم که میتونید با دستور crontab -e واردش شوید . بعد که واردش شدید چنین گزینه هایی ممکن است داشته باشد 
@reboot /bin/bash /etc/private.sh
یک چنین چیزهایی . پاک میکنید و ریبوت . روش پاک کردن از طریق اسکریپت اگر درست انجام دهید راحت تر هست .

**Comment by Mehranhich** [comment]
خب ممنون الان طبق تصویری ک ارسال کردم کدوم تانل انجام شده؟

**Comment by Mehranhich** [comment]
![Capture](https://github.com/Azumi67/6TO4-GRE-IPIP-SIT/assets/119574380/392d4606-ce71-44a8-ad13-8d68262534f5)
چطوری باید پاک کنم 
4رو زدم گیر کرد

**Comment by Azumi67** [comment]
> خب ممنون الان طبق تصویری ک ارسال کردم کدوم تانل انجام شده؟

اون تصویر راهنما بود . شما با ip a باید نام رو پیدا کنید و

**Comment by Azumi67** [comment]
> ![Capture](https://private-user-images.githubusercontent.com/119574380/337930052-392d4606-ce71-44a8-ad13-8d68262534f5.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4NzgwNjIsIm5iZiI6MTcxNzg3Nzc2MiwicGF0aCI6Ii8xMTk1NzQzODAvMzM3OTMwMDUyLTM5MmQ0NjA2LWNlNzEtNDRhOC1hZDEzLThkNjgyNjI1MzRmNS5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQyMDE2MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNTY0YmQzYTg2N2ExYWQ2MWQxMzliZWJlMzkzMjRlYzAxMmY4NGQxM2QwNjAzYWNkMjMwMjk4NGRhNDY3YjNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mciuc7j29ErDciiXwap-OhS6YGpmFR-rRFImn_ONQpQ) چطوری باید پاک کنم 4رو زدم گیر کرد

یک رو میزدید

**Comment by Mehranhich** [comment]
![Capture](https://github.com/Azumi67/6TO4-GRE-IPIP-SIT/assets/119574380/b2b209af-f549-4acf-9c6f-77c2c54c2b42)
دوباره میزنم این میاد!!

**Comment by Azumi67** [comment]
به صورت موقت میتونید 
sudo EDITOR=nano crontab -e
