### ISSUE TITLE
نحوه کانفیگ کردن پنل برای تانل :  Vxlan

### ISSUE THREAD

**Issue by Sharevex** [Azumi67/6TO4-GRE-IPIP-SIT#44]
سلام و درود خسته نباشین ، بابت همه زحماتی که میکشید واقعا ممنونم ازتون
فقط جسارتا یک سوال داشتم ، برای تانل های  vxlan ، و به طور کلی برای تانل های این اسکریپت ، باید پنل روی هر دو تا سرور نصب باشه ؟!
و اینکه برای روش vxlan ، سرور ایران من روی آیپی 6 اختلال میندازه ، ولی روی آیپی 4 اوکیه ، کدوم روش رو پیشنهاد میکنین ، تعداد یوزرماکسیمم 300 نفر هستش ( آنلاین همزمان نهایتا 70 نفر )
ممنون میشم راهنمایی بفرمایین 
سپاسگزارم

**Comment by Azumi67** [comment]
سلام مرسی. پنل فقط کافیه خارج باشه. در صورت تانل یا پورت فوروارد doko نیاز به پنل سرور ایرانم دارید. اگر از تانل دیگری استفاده میکنید نیازی به پنل در سرور ایران ندارید. از ایپی های vxlan برای پورت فوروارد و target address استفاده میکنید. سه روش در حال حاضر برای vxlan قرار داده شد که هر کدوم که بهتر است باید استفاده کنید. هر سرور بسته به اختلالات میتونه متفاوت باشد. من در مورد یوزر و سایر از این قیبل موارد به دلیل اینکه در اینکار نیستم اطلاعی ندارم.

**Comment by Sharevex** [comment]
با سلام مجدد ، بسیار ممنونم ازتون ، پس اگه از vxlan استفاده کنم باید روی سرور ایران هم پنل نصب باشه ، درسته ؟
ممنونم ازتون ، واقعا محبت فرمودین

**Comment by Azumi67** [comment]
نه حتما نیازی نیست . به طور مثال من fdb vxlan و پروژه پورت فوروارد خودم رو استفاده میکنم. پنلی هم ندارم. از open vpn استفاده میکنم.

**Comment by Azumi67** [comment]
نه حتما نیازی نیست . به طور مثال من fdb vxlan و پروژه پورت فوروارد خودم رو استفاده میکنم. پنلی هم ندارم. از open vpn استفاده میکنم.

**Comment by Sharevex** [comment]
بسیار هم عالی، خیلی محبت فرمودین کامل متوجه شدم ، شرمنده که دیروقت مزاحمتون
شدم ، شب خوبی رو داشته باشین.❤️

**Comment by Azumi67** [comment]
شما هم همچنین. خواهش میکنم

**Comment by Sharevex** [comment]
سلام مجدد ، وقتتون بخیر
ببخشید من مجددا مزاحمتون میشم ، دیتاسنتر ایران من کلا روی ipv6 لوکال اختلال میندازه ، آیپی های مربوط  ، نتونستم با vxlan تانلی برقرار کنم که کار کنه واسم ، یعنی دقیق متوجه نمیشم  vxlan مثل gre6 یا اونیکی روش ها ، آیا لرتباط لوکال برقرار میکنه یا اینکه پورت فروارد انجام میده ، و اگه پورت فروارد هست چطور ازش استفاده کنم 
 اسکریپت rathole که مشکل نصب داشت یه فایل toml باید بود ، که پیدا نمیکرد ، یا اینکه من باید فایلش رو میساختم 
 ممنون میشم یه توضیح مختصر راجب نحوه ساخت کانفیگ از نوع local ipv4  یا private ipv4 بهم بدین که بتونم یه تانل درست بر بستر این نوع از آیپی ها برقرار کنم ، سپاس بیکران از همه زحماتتون

**Comment by Azumi67** [comment]
سلام. آموزشش واضح نوشته شده دیگر. این تانل بین دو سرور هست . بعد از این تانل باید دو تا فوروارد انجام دهید . در مورد rathole باید دقت کنید که اگر سرور تون سیستم عامل قدیمی داره از روش کامپایل استفاده کنید و اگر از سیستم عامل جدید هستید از روش بایناری استفاده کنید . خود اسکریپت toml رو میسازه و مشکلی در این زمینه نداره. یک نفر دیگه هم در مورد همین پروژه اسکریپت ساخته و میتونید اون هم تست کنید . داخل خود پروژه ام، ایشون هم لینکشو گذاشتم .

**Comment by Sharevex** [comment]
یعنی بعد از انجام تانل vxlan ، نیازی به نصب پنل روی سرور ایران نیست ؟ مشکل من اینه دقیق متوجه نمیشم که  پس از انجام تانل vxlan ، چطور پورت فورواردینگ رو انجام بدم ، یعنی علاوه بر vxlan ، باید از یه تانل دیگه مثل Rathole هم استفاده کنم ؟!

**Comment by Azumi67** [comment]
بله . بعد از کانفیگ vxlan و اطمینان از پینگ دادن بین هر دو آی‌پی، میتونید از رت هول هم استفاده کنید.

**Comment by Azumi67** [comment]
فقط پنل در سرور خارج برای ساخت کانفیگ داشته باشد .

**Comment by Sharevex** [comment]
الان متوجه شدم ، پس vxlan تانل بین دو سرور برقرار میکنه و rathole پورت فرواردینگ رو انجام میده . بسیار ممنونم ازتون ، شرمنده مزاحمتون شدم

**Comment by Azumi67** [comment]
خواهش میکنم
