### ISSUE TITLE
مشکل no interface available 

### ISSUE THREAD

**Issue by nika1367** [Azumi67/6TO4-GRE-IPIP-SIT#45]
با سلام سرور خارج بعد ریبوت تانلش از کار میفته و وقتی وضعیتشو در قسمت You are viewing the status of your current tunnels میگیرم میزنه no interface available و مجدد باید اسکریپت نصب کنم تا ران بشه ! مدل کانفینگ vx+ipsec

سیستم عامل هم مجدد نصب شد ولی همین مورد تکرار میشه بعد ریبوت میپره

**Comment by Azumi67** [comment]
سلام. اسکریپت دیگری که نصب نمیکنید ؟ چون اگر دستورات کرون حذف بشه، تانل بعد از ریبوت از کار میوفته .به من بگید کدوم گزینه رو انتخاب کردید که پس از امتحان یک نگاه میکنم و نتیجه رو میگم .

**Comment by nika1367** [comment]
> سلام. اسکریپت دیگری که نصب نمیکنید ؟ چون اگر دستورات کرون حذف بشه، تانل بعد از ریبوت از کار میوفته .به من بگید کدوم گزینه رو انتخاب کردید که پس از امتحان یک نگاه میکنم و نتیجه رو میگم .

درود بر شما .... نه کاملا خام هستش سرور با آپدیت سیستم عامل اوبونتو 20 و 22 هم تست کردم نشد
 من چند بار تست کردم روی حالت p2p ipsec ورژن ایپی 6 گزینه یک خارج رو تست کردم بعد ریبوت میزنه no interface available
قسمت جالبش اینه الان گفتم بزارم حالت گزینه bridge تست کنم دیدم بعد ریبوت وضعیت تانل vx Status: Online هستش ! مجدد روی حالت p2p گزینه خارج زدم مجدد بعد ریبوت میپره انگار روی گزینه خارج p2p میپره !

**Comment by nika1367** [comment]
> سلام. اسکریپت دیگری که نصب نمیکنید ؟ چون اگر دستورات کرون حذف بشه، تانل بعد از ریبوت از کار میوفته .به من بگید کدوم گزینه رو انتخاب کردید که پس از امتحان یک نگاه میکنم و نتیجه رو میگم .

موضوع دیگر هم سوای این موضوع بالا موقع uninstall  سروریسهای فوق پیام 
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.Unable to retrieve FDB remote IP
البته بعدش چک میکنم اینترفیس پاک شده ولی key سکرت همچنان موجوده..

**Comment by Azumi67** [comment]
خب من الان نگاه کردم و داخلش یک غلط املایی داشتم. الان باید هم درست پاک کنه و هم p2p ipv6 بعد از ریبوت هم به درستی کار کنه.

**Comment by nika1367** [comment]
با تشکر فراوان از زحمات شما اوکی شد
