### ISSUE TITLE
با GRE6 پینگ دارم ولی تانل با دکومودور قطع میشه

### ISSUE THREAD

**Issue by alamdari86** [Azumi67/6TO4-GRE-IPIP-SIT#46]
سلام و عرض ادب و خسته نباشید
من یه مشکلی دارم ، در پیامهای قبلی دوستان هم خوندم شبیه بود ولی این مورد نبود
من با GRE6 آیپی لوکال رو میگیرم و با دکومودور فوروارد میکنم و از بابت پینگ بین دوتا سرور هم هیچ مشکلی ندارم و همیشه برقرار هست ولی بعد یکی دو روز ، پینگ بین دوتا سرور برقرار است ولی کانفیگ ها قطع میشن، مجبورن باید ریبولد بکنم تا درست بشه، مشکل از چی میتونه باشه؟
و سوال دیگه اینکه بین GRE6 و 6TO4 کدومش بهتره؟

**Comment by Azumi67** [comment]
سلام . اگر‌ پینگ دارید ممکنه مشکل از خود کانفیگ شما باشه . ببینید با ریست x-ray پنل، کانفیگتون دوباره کار می‌کنه یا نه . کانفیگ های مختلف تست کنید .روشهای زیادی در اون اسکریپت قرار دادم . باید خودتون تست کنید .

**Comment by alamdari86** [comment]
ممکنه ارتباطی به mtu ها داشته باشه؟
 سوال دیگه اینکه بین GRE6 و 6TO4 کدومش بهتره؟

**Comment by Azumi67** [comment]
نمیتونم بگم کدوم بهتره . الان سرورهای ایران خیلی اختلال داره . بازم میگم هر روشی که بهتر جواب بده رو کانفیگ کنید .mtu هم پایین تر ببرید و بررسی کنید

**Comment by alamdari86** [comment]
ممنون
