### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Kup1ng** [Azumi67/6TO4-GRE-IPIP-SIT#47]
سلام، خسته نباشید، با تشکر از زحماتتون یک سیوالی داشتم که ممنون میشم بهم جواب بدید

در تانل ip6ip6 مصرف ترافیک سرور ایران حدودا چند برابر میشه ؟
و آیا تفاوتی در مصرف ترافیک در سرور ایران موقع تانل ip6ip6 single و ip6ip6 multiple وجود داره ؟

باتشکر از شما

**Comment by Azumi67** [comment]
سلام. داخل گروه یک بار توضیح دادم . اما بهترین راه اینه که دو کانفیگ یکسان بار تداول مصرف یکسان در یک بازه زمانی خاص را با و بدون این روش تست کنید و خودتون محاسبه کنید . چون حساب بر اساس فقط ریاضی و بدون در نظر داشتن تمام فاکتور ها کار سختیه .
