### ISSUE TITLE
Centos

### ISSUE THREAD

**Issue by nodroon** [Azumi67/6TO4-GRE-IPIP-SIT#48]
سلام

این اسکریپت برای centos هم تولید می کنید؟

**Comment by Azumi67** [comment]
سلام. راستش نمی‌دونم . فعلا پروژه های دیگه مونده که کامل کنم .

**Comment by nodroon** [comment]
فکر نکنم زیاد زمان بر باشه براتون

**Comment by AerEbi** [comment]
منم همین مشکل رو تو CentOS دارم. چون واقعن نیازه.
ممنون میشم وقت داشتید برای CentOS هم انجام بدید.

**Comment by Hmdrf** [comment]
فک می کنم تو centos7  مشکل زیزساختی وجود دار من با sit و gre تبا bash  فایل ونل ایجاد کردم، کارت شبکه ایجاد شد ولی امکان پینگ وجود نداشت بازم تجربه شما بیشتره اگر  راهکاری پیدا کردید ممنون میشم راهنمایی کنید

**Comment by Azumi67** [comment]
دوست دارم این اسکریپت را برای CentOS هم آماده کنم اما هم توان جسمی نمی گذاره و هم در حال آپدیت چندین روش و تانل هستم و وقت زیادی میخواهد . اگر از این مورد آگاهی دارید میتونید اسکریپت رو برای CentOS بهینه کنید و به پروژه اضافه کنید .

**Comment by Hmdrf** [comment]
من به در بسته خوردم  تونلی که تو ابونتو کار می کنه توی centos ، ping نمی ده ، 
`#!/bin/bash

# Ensure required kernel modules are loaded
modprobe sit
modprobe ip6_tunnel

# Create and configure the SIT tunnel
ip tunnel add localtunnel mode sit remote IPv4(remote) local IPV4(local)
ip -6 addr add fd44:fa41:f646::1/48 dev localtunnel
ip link set localtunnel mtu 1500
ip link set localtunnel up

# Create and configure the GRE tunnel
ip -6 tunnel add gretap mode ip6gre remote fd44:fa41:f646::2 local fd44:fa41:f646::1
ip addr add 172.16.1.1/30 dev gretap
ip link set gretap mtu 1500
ip link set gretap up
`

**Comment by Aghaman** [comment]
منم نیاز دارم واقعا مخصوصا vxlan رو من خودم کدهای دستی حتی 1 به چند و چند به چند برای centos دارم ولی خب اسکریپت به این کاملی جای centos خالیه

**Comment by Azumi67** [comment]
متوجهم . چندین روش دیگه هم مونده که می‌خوام اضافه کنم و بعد شاید اینم اوکی‌ کنم . متاسفانه به چند نفر گفتم که در این کار کمک کنند اما چون یکم چون اسکریپت حجیم و شلوغه ، براشون وقت گیره . حالا خودم ببینم میتونم بعدا کاری کنم .
