### ISSUE TITLE
اضافه کردن پرایوت آی پی 6

### ISSUE THREAD

**Issue by alphamanrays** [Azumi67/6TO4-GRE-IPIP-SIT#49]
سلام مهندس عزیز خیلی ممنون از اسکریپت های خفنتون من یه سوال داشتم من یه سرور اختصاصی ایران دارم و 17 تا خارج و یکبار 6 تو 4 رو اجرا کردم برای یکی از خارج ها و پرایوت ای پی گرفتم حالا برای اینکه سرور جدید تانل کنم برای ایران مجدد همون آی پی 6 رو تولید میکنه چطور میتونم یه رول جدید برای سرور ایران و خارج تعریف کنم ؟در حقیقت من میخوام به تدریح سرور های خارج اضافه کنم به  تانل 6 تو 4 سرور ایران و با تانل دکودمودور آی پی 6 کار کنم

**Comment by Azumi67** [comment]
سلام داخل تلگرام هم گفتم . فعلا فقط ده سرور و پنج ایران اضافه شده و قابلیت اضافه کردن تدریجی سرور ها هم موجوده .
بهتره بین چند سرور ایران پخش کنید که اگر یک سرور ایران مشکل داشت ،‌سرور ایران دیگر کار کند .
