### ISSUE TITLE
private ipv6

### ISSUE THREAD

**Issue by babakazizigithub** [Azumi67/6TO4-GRE-IPIP-SIT#5]
درود

چرا  روش Geneve + NATIVE + IP6TNL + GRE6 | ایپی پرایوت 6 توی لیست اسکریپت نیست؟  ممنون میشم راهنمایی کنید

سپاس

**Comment by Azumi67** [comment]
سلام. باید باشه .قبلا با ریبوت از کار میوفتاد ولی الان درسته

**Comment by babakazizigithub** [comment]
> سلام. باید باشه .قبلا با ریبوت از کار میوفتاد ولی الان درسته

ممنون از پاسخگوییتون 
متاسفانه همه رو تست کردم نیست و با اون شاتی که توی گیت هابتون هست پیداش نکردم - میشه لطفا یه شات اینجا قرار بدید که دقیقا کدومه

ممنونم

**Comment by Azumi67** [comment]
![Screenshot 2024-02-29 010755](https://github.com/Azumi67/6TO4-GRE-IPIP-SIT/assets/119934376/aba60fce-f077-4db6-8cfd-f0fa8fb03ca7)
