### ISSUE TITLE
قطع شدن تانل Vxlan بعد از ریبوت

### ISSUE THREAD

**Issue by Gholamreza29** [Azumi67/6TO4-GRE-IPIP-SIT#50]
با سلام
تشکر از زحمات شما و اسکریپت خوبتون. من تونل Vxlan تست کردم. اما بعد از ریبوت سرور تونل قطع میشه و باید از اول مراحل رو انجام بدم. با چندتا سرور تست کردم و همین مشکل بود.
اینم بگم که فقط سرور خارج رو ریبوت میکردم که بعد از ریبوت ارتباط قطع میشد و مراحل رو باید از اول انجام میدادم.

**Comment by Azumi67** [comment]
سلام. لطفاً گزینه دقیق و روش‌ دقیق رو بهم بگید که من هم تست کنم . داخل ip a ببینید اینترفیسش هست یا خیر. مورد دیگر اینکه اسکریپت دیگری بعد از انجام اسکریپت من هم انجام دادید ؟

**Comment by Gholamreza29** [comment]
اینترفیسش هست
regular vxlan>>FDB VXLAN>>IPv4

**Comment by Azumi67** [comment]
> اینترفیسش هست regular vxlan>>FDB VXLAN>>IPv4 اسکریپت دیگه ای نصب نیست

پس اگر امکان دارد یک کاری کنید . ریبوت کنید و ببینید اینترفیسش هنوز هست یا خیر . اگر اینترفیس بمونه پس مشکل چیزی دیگری هست
