### ISSUE TITLE
GRE6 + IPSec

### ISSUE THREAD

**Issue by Mohammadaminsdr** [Azumi67/6TO4-GRE-IPIP-SIT#51]
احتمال ایران اکسس داره ؟ چون بدون IPSec زدیم نشد ولی با IPSec زدیم شده همون سرور

**Comment by Azumi67** [comment]
نه ربطی به اینها نداره . من خودم با IPsec هستم

**Comment by Mohammadaminsdr** [comment]
Enter the Secret key: ihaebfguhebvrughbwuiherbvsijdfuhdfg

هر چقدر زیاد باشه شناسایش سخت تر میشه یا ربطی نداره ؟؟

**Comment by Azumi67** [comment]
بله اما یک آپدیت برای IPsec بعدا میدم .

**Comment by Mohammadaminsdr** [comment]
ممنون از شما منتظر اپدیتیم :)

**Comment by Azumi67** [comment]
شاید فردا یک آپدیت بدم .فعلا داخل تست قرار دادمش.
