### ISSUE TITLE
راهنمایی در رابطه با geneve

### ISSUE THREAD

**Issue by Gholamreza29** [Azumi67/6TO4-GRE-IPIP-SIT#53]
با سلام
من قبلا تونل geneve  رو راه اندازی کردم و مشکلی نداشت. اما الان از یه دیتاسنتر جدید سرور گرفتم که از سمت دیتاسنتر فایروال فعاله بخاطر همین هرچی تلاش کردم نشد که نشد. با پشتیبانی که تماس گرفتم گفتند بگید چه پورتی رو نیاز دارید تا باز کنیم. اما تا جایی که میدونم geneve پورت خاصی رو درگیر نمیکنه. اگر میشه یه راهنمایی کنید که من بهشون بگم مثلا پورت رو فعال کنند. یا قسمت مشخصی از فایروال رو غیرفعالش کنند. با تشکر

**Comment by Azumi67** [comment]
سلام. Geneve پورت 6081 رو نیاز داره و اینکه باید پرایوت آی‌پی های هر دو طرف به رول فایروال اضافه بشه.
