### ISSUE TITLE
غیرفعال شدن پینگ

### ISSUE THREAD

**Issue by Mohammadaminsdr** [Azumi67/6TO4-GRE-IPIP-SIT#54]
سلام وقتتون بخیر جدیدا به یه مشکلی از یکی از سرور ها خوردن اینکه gre6 + ipsec میزنیم بعد یک روز پینگ نمیدن حتی دیفالت روت رو هم اوکی کردیم ولی باز قطع میشن مشکل از چی میتونه باشه بخش کرون هم چک کردم اوکی بود همه چی

**Comment by Azumi67** [comment]
سلام‌. روی بعضی سرور های ایران و اون خارج مربوطه،‌بعضی روش ها اختلال دارند . باید یا روش رو عوض کنید یا سرور خارج رو .
و برای IPsec هم ریست تایمر بذارید.
