### ISSUE TITLE
عدم دسترسی به پرایوت ایپی

### ISSUE THREAD

**Issue by amirng** [Azumi67/6TO4-GRE-IPIP-SIT#55]
سلام وقت بخیر باشه
الان من روی دیتاسنتر هاست ایران با شبکه رسپینا دارم کار میکنم
اما جواب نمیده
ینی روی سرور خارج میزنم
روی سرور ایران میزنم هاست ایران ولی جواب نمیده icmp_seq=2 Destination unreachable: Address unreachable 
واسه چیه این خطا
mtu هم دستی عوض کردم عدد رندوم زدم باز نشد
روی یک سرور ایران دیگه تست کردم اوکی بود ولی حتی از اون ایرانه به هاست ایران نمیشه بازم

**Comment by amirng** [comment]
من از مولتی سرور استفاده میکنم
۲ سرور ایران
۱ سرور خارج
6tO4 Multiple Servers از این روش استفاده میکنم

**Comment by Azumi67** [comment]
سلام . شما دو راه دارید. روی اون سرور ایرانی که این مشکل هست باید با خارجی دیگری این روش رو تست کنید یا روش رو از sit به روش‌هایی دیگر تغییر بدید و ببینید کار میکند یا خیر.

**Comment by amirng** [comment]
با همین روش یه سرور روی یک سرور خارج دیگه تست کردم نشد
چه روشی پیشنهاد میکنید؟
متوجه نشدم از کجا تغییر بدم؟

**Comment by Azumi67** [comment]
روش رو از sit به طور مثال به vxlan تغییر میدید یا gre6 . در اون سرور ایران در حال حاضر شما نمیتوانید با اون روش وصل بشید. به طور مثال اگر سرور خارج 1 با ایران 1 مشکل داره. این احتمال هست که خارج دوم با ایران یک مشکل نداشته باشه.

**Comment by amirng** [comment]
add tunnel "sit0" failed: No buffer space available
RTNETLINK answers: File exists
RTNETLINK answers: File exists
╰─────────────────────────────────────────────────────────╯
✨ Adding commands...
Do you want to set the MTU [6to4]? (yes/no): no
✔ Private ip added successfully!
✔ Cronjob added successfully!
✔ keepalive service Configured!
Pinging failed: Command '['ping', '-c', '2', '2002:801b::1']' returned non-zero exit status 1. 
✨ Configuring...
╭─────────────────────────────────────────────────────────╮
─────────────────────────────────────────────────────────
Enter the number of additional IPs for the GRE6 tunnel: 1
add tunnel "ip6gre0" failed: No buffer space available
RTNETLINK answers: File exists
RTNETLINK answers: File exists
Do you want to set the MTU [GRE6]? (yes/no): no
─────────────────────────────────────────────────────────
Created IPv6 Addresses Server 1:
+---------------------------+
| 2002:801a::2               |
| 2002:802a::2               |
+---------------------------+
(Please wait,Azumi is pinging...
PING 2002:801a::1(2002:801a::1) 56 data bytes
From 2002:801a::2 icmp_seq=1 Destination unreachable: Address unreachable
From 2002:801a::2 icmp_seq=2 Destination unreachable: Address unreachable

--- 2002:801a::1 ping statistics ---
2 packets transmitted, 0 received, +2 errors, 100% packet loss, time 1003ms
✔ Cronjob added successfully!
✔ GRE6 Configuration Completed!
Press Enter to continue...





الان از روش مولتی سرور بخش GRE6 Multiple Servers استفاده کردم
اول سرور خارج سپس سرور ایران با این خطا باز مواجه شدم

**Comment by Azumi67** [comment]
داخل گیت هاب نوشتم .buffer space وقتی میده باید تانل‌ها یا بهتره بگم اینترفیس های قدیمی رو پاک کنید وگرنه کانفیگ انجام نمیشه .

**Comment by amirng** [comment]
Do you want meh to find the main interface automatically? (yes/no): yes
Do you want to set the MTU [Vxlan]? (yes/no): no
PING 30.0.0.2 (30.0.0.2) 56(84) bytes of data.
From 30.0.0.1 icmp_seq=1 Destination Host Unreachable
From 30.0.0.1 icmp_seq=2 Destination Host Unreachable

--- 30.0.0.2 ping statistics ---
2 packets transmitted, 0 received, +2 errors, 100% packet loss, time 1004ms
pipe 2
✔ Vxlan ip added successfully!
✔ Cronjob added successfully!
✔ keepalive service Configured!
Please Wait, Azumi is pinging...
Pinging failed: Command '['ping', '-c', '2', '30.0.0.2']' returned non-zero exit status 1. 
✨ Vxlan FDB With Bridge Configured
Created IPv6 Addresses Kharej Server 
+---------------------------+
|          30.0.0.1         |




این سرور خارج




✨ Installing Bridge..
Bridge Installation complete.
─────────────────────────────────────────────────────────
Do you want meh to find the main interface automatically? (yes/no): yes
Do you want to set the MTU [Vxlan]? (yes/no): no
PING 30.0.0.1 (30.0.0.1) 56(84) bytes of data.
From 30.0.0.2 icmp_seq=1 Destination Host Unreachable
From 30.0.0.2 icmp_seq=2 Destination Host Unreachable

--- 30.0.0.1 ping statistics ---
2 packets transmitted, 0 received, +2 errors, 100% packet loss, time 1023ms
pipe 2
✔ Vxlan ip added successfully!
✔ Cronjob added successfully!
✔ keepalive service Configured!
Please Wait, Azumi is pinging...
Pinging failed: Command '['ping', '-c', '2', '30.0.0.1']' returned non-zero exit status 1. 
✨ Vxlan FDB With Bridge Configured
Created IPv6 Addresses IRAN Server 
+---------------------------+
|          30.0.0.2         |
+---------------------------+
Press Enter to continue...




اینم سرور ایران

**Comment by Azumi67** [comment]
به شما گفتم . ممکنه یک روش در یک سرور ایران کار نکند و یک روش کار کند. ممکنه همه کار نکند . باید با سرور های خارج مختلف تست کنید یا حتی icmp تست کنید . وقتی یک روش کار نمیکند روش دیگری را باید تست کنید. حتما اطمینان پیدا کنید که تانل های قبلی را پاک کرده باشید

**Comment by amirng** [comment]
دستور پاک کردن تانل های قبلی رو میفرمایید؟
sudo ip link delete vxlan
از این استفاده میکنم درسته؟

**Comment by amirng** [comment]
حقیقتا کلافه شدم هرچی میزنم نمیشه

**Comment by amirng** [comment]
تمام روش ها رو تست کردم فقط یک روش جواب داد
اونم توی تک سرور تک سرور
vxlan 
کار کرد
مولتی سرور نمیشه زد اینو؟

**Comment by Azumi67** [comment]
پس اون روش براتون خوبه . مولتی سرورش رو دارم آماده میکنم . زمان میخواهد .
