### ISSUE TITLE
ریست تایمر مولتی سرور

### ISSUE THREAD

**Issue by Mohammadaminsdr** [Azumi67/6TO4-GRE-IPIP-SIT#56]
سلام وقتتون بخیر ما ریست تایمر زدیم قطع میشه میخوایم برداریم چطور باید برداریم از رو سرور ها گزینه اش تو اسکریپت نیست

**Comment by Azumi67** [comment]
سلام. ریست تایمری ندارد به جز مگر اینکه ipsec را کانفیگ کرده باشید .

**Comment by Mohammadaminsdr** [comment]
بله ipsec زدیم و اینکه روش عای anycast با بدون anycast چه فرقی دارن ؟

**Comment by Azumi67** [comment]
روش عادی بدون اینکه بر روی سرور لود بالانس برود انجام میشود و روش دیگر از anycast استفاده میکند.
