### ISSUE TITLE
Sit tunnel for Single Server

### ISSUE THREAD

**Issue by Sharevex** [Azumi67/6TO4-GRE-IPIP-SIT#57]
سلام وقتتون بخیر ، خسته نباشین ، بابت همه زحماتتون واقعا ممنونم
فقط دو تا سوال داشتم ،کدوم پروتکل از تانل ها که توی اسکریپت هست بر پایه ipv4 انجام میشه ؟ یعنی خروجی به صورت ipv4 برای تانل کردن باشه ، و اینکه آیا تانل Sit که برای دو خارج و دو ایران هست به صورت سینگل هم میشه استفاده کرد ؟

**Comment by Azumi67** [comment]
سلام. geneve و vxlan ، پرایوت ایپی های 4 هم دارند . در مورد سوال دوم هم بله میشه به صورت سینگل هم همون رو کانفیگ کرد

**Comment by Sharevex** [comment]
مرسی مرسی خانم مهندس ، شرمنده کردین ، ممنونم ازتون 
ببخشید که مزاحم شدم
