### ISSUE TITLE
امکان گرفتن چند ایپی 

### ISSUE THREAD

**Issue by alimahjoub** [Azumi67/6TO4-GRE-IPIP-SIT#59]
سلام لطفا اگه میشه تو 6tO4 + IPsec Multiple Servers تغییری اعمال کنید بشه چند تا آیپی گرفت

**Comment by Azumi67** [comment]
سلام . این مورد باعث اختلال در IPsec می‌شود .

**Comment by alimahjoub** [comment]
نمیشه همون رنج آیپی های قبل رو به 6to4 برگردونید؟

**Comment by alimahjoub** [comment]
2002:841b::1
این

**Comment by Azumi67** [comment]
به دلیل اینکه این موارد پیش نیاز موارد دیگر هست و حجم اسکریپت خیلی زیاد است ، دستبرد به این موضوع زمان زیادی نیاز دارد و کاری بیهوده هست چون تغییری در نتیجه ایجاد نمیشود.
