### ISSUE TITLE
6to4

### ISSUE THREAD

**Issue by Mohammadaminsdr** [Azumi67/6TO4-GRE-IPIP-SIT#6]
سلام وقت بخیر 
تو اپدیت های جدید اسکریپت وقتی 6to4 انجام میدم بعد یه مدت از کار میوفتن یعنی هر دو طرف پینگ نمیدن فیلتر نمیشن فقط انگار قطع میشن مشکل از چی میتونه باشه  ؟ ممنون میشم راهنمایی کنید

**Comment by Azumi67** [comment]
سلام. آپدیت به اونها کاری نداشته . باید ببینید که سرور شما یا اون روش ها اختلال داره یا نه . اگر 6ro4 عادی رو انجام میدید که خیلی وقته روی بعضی سرور ها اختلال دارن . میتونید ویدیوی های داخل یوتیوب هم نگاه کنید و به صورت دستی بسازید و ببینید چطوریه .

**Comment by Azumi67** [comment]
فکر کنم برای مولتی سرور در حال حاضر gre6 و geneve که برای مولتی سرور geneve باید صبر کنید تا اضافه کنم . 
برای حالت تک سرور هم gre6 و gre6tap خوبه و geneve ,هم خوبه .
