### ISSUE TITLE
حجم مصرفی بالا در استفاده از روش های اسکریپت

### ISSUE THREAD

**Issue by BenyaminMoadab** [Azumi67/6TO4-GRE-IPIP-SIT#61]
سلام وقت بخیر
میخواستم ببینم علت اینکه از روش های این اسکریپ استفاده میکنم معمولا حجم چندباری استفاده میکنه یعنی وقتی رو پنل 20 گیگ استفاده میشه رو سرور 60 گیگ حجم میزنه
علتش چیه؟

**Comment by Azumi67** [comment]
سلام. لطفاً در این مورد در گوگل مطالعه بفرمایید . مبحث طولانی هست .

**Comment by BenyaminMoadab** [comment]
دقیقا  چه چیزی رو باید مطالع کنم ؟ کاش ی لینکی قرار میدادین
واینکه واقعا راهکاری برای حجم مصرفی کمتر نیست؟

**Comment by BenyaminMoadab** [comment]
چون من فک میکردم فقط آپلود رو میاد 2.5 برابر میکنه اما چندروزه دقت میکنم اناگار دانلود هم میاد  برابر حدودا حساب میکنه

روشی هاییم که تست کردم :
Ip6Ip6 + IpSec  +  Tunnel Gost
GRE6 + IpSec  +  Tunnel Gost
GRE6    +  Tunnel Gos
Xvlan + Ipsec + Tunnel Gost
تو همه این  روش ها دانلود حدود 2 برابر و آپلود 2.5 برابر میزنه
مثلا مقدار دانلود اینباند ها 7 گیگ باشه توی overview پنل حجم کلی دانلود هارو 14 الی 15 گیگ میزنه توی سرور ایران هم حجمی که از سرور کم میکنه حدودا 12 الی 13 گیگ هستش

واقعا نیمدونم از این روش ها هستش یا تونل گوست ممنون میشم راهنمایی کنید

**Comment by Azumi67** [comment]
چند نفر از کسانی که استفاده میکردن به من گفتند تا 1.4 مصرف بیشتر داشتند .این موارد بررسیشون نیاز به زمان زیاده داره و در حال حاضر خارج از توانایی من هست .

**Comment by BenyaminMoadab** [comment]
درسته باشه ممنون
من فقط خواستم اطلاع بدم و بپرسم شاید راهکاری باشه
