### ISSUE TITLE
6to4 خالی تک سرور 

### ISSUE THREAD

**Issue by Mohammadaminsdr** [Azumi67/6TO4-GRE-IPIP-SIT#62]
سلام وقت بخیر ما تانل رو بین سرور ها برقرار میکنیم و اوکیه تا 1 روز ولی قطع میشه ارتباط باید بیایم پاک از دوباره کانفینگ کنیم با اینکه مسیر روت رو عوض میکنیم که پاک نشن

**Comment by Azumi67** [comment]
سلام کسی این مشکل رو داشتند و یا پاک کردن انواع bbr ها براشون درست شد . چون این مشکل اسکریپت نیست .اینجا رو مطالعه کنید.  https://github.com/Azumi67/6TO4-GRE-IPIP-SIT/issues/58
ممکنه هم حتی به خاطر اختلال سرور شما باشه .
