### ISSUE TITLE
مشکل در mtu

### ISSUE THREAD

**Issue by arash0921** [Azumi67/6TO4-GRE-IPIP-SIT#63]
سلام خیلی ممنمونم ازت بابت این اسکریپت عالی
من تانل vxlan p2p میزنم بعدش وقتی mtu تغیر میدم روی هر عددی بزارم کلا ارتباط قطع  میشه

**Comment by Azumi67** [comment]
سلام . دقیقا نمیشه گفت مشکل قطعی شما چیه . ممکنه به دلیل udp باشه یا فایروال ufw یا اختلال یا سایر موارد . برای mtu هم میتوانید به صورت اتوماتیک بذارید.
من بعد از اسکریپت لوکال‌تان چندین روش دیگر برای vxlan میارم
