### ISSUE TITLE
امکان استفاده از پرایوت ایپی در مولتی سرور

### ISSUE THREAD

**Issue by alimahjoub** [Azumi67/6TO4-GRE-IPIP-SIT#64]
سلام خسته نباشی ازومی اگه ممکنه رو مولتی سرور هم پرایوت آیپی اضافه کن.

ممنون

**Comment by Azumi67** [comment]
سلام مرسی. داخل مولتی پرایوت به نام 6to4 هست . داخل مولتی ده خارج پنج ایران هم هست .

**Comment by alimahjoub** [comment]
منظورم این مدل آیپی هست
fd1d:fc98:b73e:b381::2

**Comment by alimahjoub** [comment]
چون رو 4to6 تست زدم‌آیپی ۴ خارج فیلتر میشه
