### ISSUE TITLE
ip6ip6

### ISSUE THREAD

**Issue by hosseinebadi1128** [Azumi67/6TO4-GRE-IPIP-SIT#65]
سلام مناسکریپت میزنم ip6ip6 انجام میشه کانفیگ کار میکنه بعد ۳یا ۴ ساعت از کار میوفته کار نمیکنه

**Comment by hosseinebadi1128** [comment]
روش ip6ip6

**Comment by hosseinebadi1128** [comment]
ایپی ۶ که میزنم پینگ میده بعد ۳ ساعت یا ۴ ساعت پینگم نمیده باید پاک کنم دوباره بزنم

**Comment by Azumi67** [comment]
سلام همین مورد رو کسی دیگه داشت . ریبیلد کردند و یک سری کارها درست شد . این جا رو بخونید.
https://github.com/Azumi67/6TO4-GRE-IPIP-SIT/issues/58#issuecomment-2208620031

**Comment by hosseinebadi1128** [comment]
bbr نصب کنم درست میشه

**Comment by Azumi67** [comment]
یه خیلی موارد بستگی داره . داخل اون تاپیک مطالعه کنید . مشکل شما رو داشتند و حل کردند .
