### ISSUE TITLE
تفاوت GRE6 با Private IP

### ISSUE THREAD

**Issue by alamdari86** [Azumi67/6TO4-GRE-IPIP-SIT#66]
سلام و عرض ادب و خسته نباشید
مهندس تفاوت gre6 و privateip در چی هست؟
از لحاظ امنیت ، سرعت و شناسایی از طرف فایروال فیلترینگ

**Comment by Azumi67** [comment]
سلام هر دو آنها تانل پروتکل هستند و پکت ها را encapsulated می‌کنند. من معمولا از سیت یه عنوان payload در gre6 استفاده میکنم .همه آنها توسط فایروال از طریق dpi و بررسی هدر پکت ها و payload شان قابل شناسایی هستند و میتواند پکت ها را که به صورت encapsulation است را بررسی کند یا میتواند به دنبال پروتکل تانل یا encapsulation مخصوصی در ترافیک مربوطه باشد یا اصلا می‌تونه به دنبال موارد نامعمول و  خاصی بگردد و شناسایی کند مثلا سایر پکت های مشخص و متداوم و interval یکسان و از طریق rate limit بیاید و استفاده از آن روش را غیر ممکن و عذاب آور کند و یا آن را دراپ کند.
