### ISSUE TITLE
علت پینگ ندادن سرور ها در روش های Xvlan

### ISSUE THREAD

**Issue by BenyaminMoadab** [Azumi67/6TO4-GRE-IPIP-SIT#67]
سلام وقت بخیر سرور های من فایروالی ندارن و وقتی xvlan هر مدلیش رو نصب میکنم متاسفانه پینگ نمیدن نصب به هم
علت چیه؟

**Comment by Azumi67** [comment]
سلام . Vxlan حتی بر روی بعضی سرور های خارج به خارج هم کار نمیکند . باید اتصال اول عوض شود که آپدیت های وایرگارد و سایر موارد تموم بشه ،‌اونم اضافه میکنم .

**Comment by BenyaminMoadab** [comment]
عجیبه

**Comment by Azumi67** [comment]
> عجیبه

حالا تلاش میکنم ترکیب sit , isatap با vxlan رو سریع تر بیارم

**Comment by BenyaminMoadab** [comment]
خیلیم عالی
و یک سوال دیگه اینکه سرعت آپلود روش XVLAN + FDP نسبت به P2P کمتر و ناپایدار تره علتش چیه؟

**Comment by Azumi67** [comment]
> خیلیم عالی و یک سوال دیگه اینکه سرعت آپلود روش XVLAN + FDP نسبت به P2P کمتر و ناپایدار تره علتش چیه؟

ان یکی از فوروارد دیتابیس استفاده میکنه و بستگی به سرور شما داره .

**Comment by BenyaminMoadab** [comment]
اهان یعنی هرچی سرور سخت افزاری قوی تر باشه بهتر عمل میکنه یا از منظر پهنای باند شبکه؟
