### ISSUE TITLE
سوالی در مورد نحوه استفاده از ترافیک شبکه در تانل gre6

### ISSUE THREAD

**Issue by mohsenrahmani145** [Azumi67/6TO4-GRE-IPIP-SIT#70]
سلام وقت بخیر خسته نباشید
من با اسکریپت شما از سرور ایران به سه سرور خارج تانل gre6 برقرار کردم
بعد از مانیتور کردن شبکه چیزی رو دیدم برام سوال ایجاد کرد
تفاوت (azumi1 - azumig61) و (azumi2 - azumig62) و (azumi3 - azumig63) در چیست؟
ایا این به منزله دوبله شده میزان مصرف ترافیک شبکه سرور ایران نیست؟
با تشکر از شما

![image](https://github.com/user-attachments/assets/aadf4ff9-4cbe-4e70-8154-d663cb3bf72a)

**Comment by mohsenrahmani145** [comment]
من تا قبل از تانل gre6 از cdn استفاده میکردم و هزینه کمتری پرداخت میکردم بابت ترافیک و تا بحال تانل نزده بودم و بعد از استفاده از تانل میزان هزینه ترافیکم به طرز چشمگیری افزایش پیدا کرده حتی هزینه پلن ها ترافیک cdn و سرور مجازی تو سایت هم بررسی کردم فرقش 200 تومن بود با این وجود بازم بیشتر از محاسبه من هزینه ترافیک میکنه

**Comment by Azumi67** [comment]
سلام. Azumi1 حدود 5.40GB ترافیک مصرفی داره و azumig61 حدود 5.14. خب تفاوت این دو تا می‌تونه به این دلایل باشه که ازومی g61 یا همون gre به دلیل تفاوت محاسبه overhead و پکت ها، مقدار متفاوتی رو نشون میده. خود SIt و در اینجا ازومی یک، پکت های آی‌پی 4 را در هدر های آی‌پی 6 encapsulated می‌کند و gre6 tunnel هم این encapsulation رو ادامه میدهد‌. هدر های اضافی باعث افزایش سایز دیتا می‌شود و هم چنین این مقدار اضافی هم ممکنه به درستی در مقدار ترافیک گزارش شده به دلیل مکانیسم های داخلی به درستی نشون داده نشه. 
یعنی چی ؟ یعنی اینکه ممکنه به دلیل control packets و overhead ، بعضی از این encapsulation protocols پکت های اضافی را در محاسبه اخر ترافیک نشون ندهند یا به دلیل اینکه مثلا بگیم چون gre6 ممکنه بعضی ها bytes ها که در ازومی یک محاسبه شده را فیلتر کند و محاسبه نشود .  
مقدار overhead مشاهده شده رو هم از داخل همون مثالی که گذاشتید میتونید به دست بیاورید .
