### ISSUE TITLE
مولتی سرور

### ISSUE THREAD

**Issue by Mohammadaminsdr** [Azumi67/6TO4-GRE-IPIP-SIT#71]
سلام وقت بخیر این روش های جدید مثل Vxlan و ... کی اضافه میشن به مولتی سرور ؟ ممنون از شما :)

**Comment by Azumi67** [comment]
سلام. فعلا دارم ویرایش لوکال آی‌پی ها رو به اسکریپت اضافه میکنم که جز لیست بوده .
