### ISSUE TITLE
سوال در مورد anycast

### ISSUE THREAD

**Issue by ghojaei1995** [Azumi67/6TO4-GRE-IPIP-SIT#72]
سلام من به روش anycast یک خارج را به سه سرور ایران تانل کردم الان خواستم یک ایران جدید هم اضافه کنم بدون اینکه در سرور خارج تانل را پاک کنم و دوباره اجرا کنم در سرور ایران چهارم anycast زدم و بدون مشکل داره کار میکنه میخواستم بپرسم حتما اجباری هست در سرور خارج تانل را پاک و مجدد اجرا کنم تا سرویس پینگ  برای سرور ایران چهارم هم اجرا بشه یا نه؟

**Comment by Azumi67** [comment]
سلام. همه سرور ها در لود بالانس قرار میگیرند ولی توصیه میشه که بین همه اونها یک keepalive هم باشد. شما میتوانید بدون keepalive یعنی بدون پاک کردن سرور‌خارج هم انجام دهید .

**Comment by Mehranhich** [comment]
در 6to4 روش anycast و بدون anycast احتمال از کار افتادن native میباشد و باید default route را فعال کنید
اینو چطور فعال کنم؟؟

**Comment by Azumi67** [comment]
> در 6to4 روش anycast و بدون anycast احتمال از کار افتادن native میباشد و باید default route را فعال کنید اینو چطور فعال کنم؟؟

موقع کانفیگ از شما میپرسد . Change default route

**Comment by Mehranhich** [comment]
خب الان همچیز رو تنظیم کردم راهی داره فعالش کنم ک چیزی قطع نشه؟

**Comment by Azumi67** [comment]
> خب الان همچیز رو تنظیم کردم راهی داره فعالش کنم ک چیزی قطع نشه؟ نه y زدم اون مرحله نه n اینتر کردم فقط

همون n حساب میشه. شما به نظرم صبر کنید و ببینید مشکلی ایجاد میشود یا خیر.

**Comment by Mehranhich** [comment]
> > خب الان همچیز رو تنظیم کردم راهی داره فعالش کنم ک چیزی قطع نشه؟ نه y زدم اون مرحله نه n اینتر کردم فقط
> 
> همون n حساب میشه. شما به نظرم صبر کنید و ببینید مشکلی ایجاد میشود یا خیر.

منظورتون همون قطع شدن تانله؟

**Comment by Azumi67** [comment]
> > > خب الان همچیز رو تنظیم کردم راهی داره فعالش کنم ک چیزی قطع نشه؟ نه y زدم اون مرحله نه n اینتر کردم فقط
> > 
> > 
> > همون n حساب میشه. شما به نظرم صبر کنید و ببینید مشکلی ایجاد میشود یا خیر.
> 
> منظورتون همون قطع شدن تانله؟

هم اون و هم از کار افتادن native ipv6

**Comment by Mehranhich** [comment]
باشه ببینم چی میشه

**Comment by Mehranhich** [comment]
استاتوس میزنم این میاد یکی از سرور ها قطع شده میخواستم چک کنم

![Capture](https://github.com/user-attachments/assets/04d8c38f-9381-4ebb-b2a3-3dfb91e2aeed)

**Comment by Mehranhich** [comment]
ادیت نداره چطوری همون سرور رو فقط اوکی کنم؟!!

**Comment by Azumi67** [comment]
> استاتوس میزنم این میاد یکی از سرور ها قطع شده میخواستم چک کنم
> 
> ![Capture](https://private-user-images.githubusercontent.com/119574380/350306413-04d8c38f-9381-4ebb-b2a3-3dfb91e2aeed.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNzU5NzIsIm5iZiI6MTcyMTM3NTY3MiwicGF0aCI6Ii8xMTk1NzQzODAvMzUwMzA2NDEzLTA0ZDhjMzhmLTkzODEtNGViYi1iMmEzLTNkZmI5MWUyYWVlZC5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOVQwNzU0MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MTk1ZTY1NThkODkzNTY4OWQ3ODNkZmFkNTFlNWIwODViYWExZWYyZTVhY2JhNjM4NjY2ZmFmMjAyNDM4MGVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kChVye-dJNo24clKfB-2KLBj3Vgqncp4FSDggnallHQ)

برای 6to4 anycast استاتوسی نوشته نشده

**Comment by Azumi67** [comment]
> ادیت نداره چطوری همون سرور رو فقط اوکی کنم؟!!

چون روش کانفیگش اینطوری هست . برید داخل همون سرور ایران و دوباره کانفیگ کنید .

**Comment by Mehranhich** [comment]
الان من 5تا سرور دارم با خراج خب و الان سرور سوم من ک ایران قطع شده حذف کردم تانل رو میخوام مجدد تانل کنم اینجور میشه
میپرسه ب چندتا سرور پینگ میگم 4
سرور اول میشه ای پی ایران 4
سرور دوم میشه ای پی خارج
سرور سوم میشه ای پی ایران 1
سرور دوم میشه ای پی ایران 2
درسته؟
چون این کارو انجام دادم ب خارج پینگ نداد الان!

**Comment by Azumi67** [comment]
یعنی چی ؟ اون موردی که می‌پرسه فقط برای keepalive هست و داخل این روش چون همه سرور ها داخل لود بالانس میرن ، نیازی به مشخص کردن کانفیگ های جداگانه ندارد. شما فرض رو بر این بگیرید که پینگ بین آی‌پی ها رو خودتون اوکی میکنید . شما یک بار خارج رو وارد میکنید . بعد هر تعداد ایران دارید رو با کانفیگ ایران وارد میکنید . حالا نوبت پینگ هست . خودتون یک سرویس پینگ بین سرور خارج و سرور ایران مربوطه ایجاد کنید. اصلا نیازی نیست دوباره سرور خارج و ایران ها رو کانفیگ کنید . در مورد سوال keepalive هم سرور اول‌ ایران شماره یک میشه و شماره چهار سرور چهارم ایران .

**Comment by Mehranhich** [comment]
> یعنی چی ؟ اون موردی که می‌پرسه فقط برای keepalive هست و داخل این روش چون همه سرور ها داخل لود بالانس میرن ، نیازی به مشخص کردن کانفیگ های جداگانه ندارد. شما فرض رو بر این بگیرید که پینگ بین آی‌پی ها رو خودتون اوکی میکنید . شما یک بار خارج رو وارد میکنید . بعد هر تعداد ایران دارید رو با کانفیگ ایران وارد میکنید . حالا نوبت پینگ هست . خودتون یک سرویس پینگ بین سرور خارج و سرور ایران مربوطه ایجاد کنید. اصلا نیازی نیست دوباره سرور خارج و ایران ها رو کانفیگ کنید . در مورد سوال keepalive هم سرور اول‌ ایران شماره یک میشه و شماره چهار سرور چهارم ایران .

اها من الان ی سرور جدید هم ساختم تانلش با خارج برقرار نمیشه نمیدونم باید چیکار کنم بعید میدونم اشتباهی هم انجام بدم

**Comment by Azumi67** [comment]
> > یعنی چی ؟ اون موردی که می‌پرسه فقط برای keepalive هست و داخل این روش چون همه سرور ها داخل لود بالانس میرن ، نیازی به مشخص کردن کانفیگ های جداگانه ندارد. شما فرض رو بر این بگیرید که پینگ بین آی‌پی ها رو خودتون اوکی میکنید . شما یک بار خارج رو وارد میکنید . بعد هر تعداد ایران دارید رو با کانفیگ ایران وارد میکنید . حالا نوبت پینگ هست . خودتون یک سرویس پینگ بین سرور خارج و سرور ایران مربوطه ایجاد کنید. اصلا نیازی نیست دوباره سرور خارج و ایران ها رو کانفیگ کنید . در مورد سوال keepalive هم سرور اول‌ ایران شماره یک میشه و شماره چهار سرور چهارم ایران .
> 
> اها من الان ی سرور جدید هم ساختم تانلش با خارج برقرار نمیشه نمیدونم باید چیکار کنم بعید میدونم اشتباهی هم انجام بدم

پس بهتره یک بار دیگه تمام سرور هارو پاک کنید و سریع کانفیگ کنید . دفعه بعد قطع شد همین کارو بکنید

**Comment by Mehranhich** [comment]
این کار رو فقط داخل خارج انجام بدم کافیه؟

> > > یعنی چی ؟ اون موردی که می‌پرسه فقط برای keepalive هست و داخل این روش چون همه سرور ها داخل لود بالانس میرن ، نیازی به مشخص کردن کانفیگ های جداگانه ندارد. شما فرض رو بر این بگیرید که پینگ بین آی‌پی ها رو خودتون اوکی میکنید . شما یک بار خارج رو وارد میکنید . بعد هر تعداد ایران دارید رو با کانفیگ ایران وارد میکنید . حالا نوبت پینگ هست . خودتون یک سرویس پینگ بین سرور خارج و سرور ایران مربوطه ایجاد کنید. اصلا نیازی نیست دوباره سرور خارج و ایران ها رو کانفیگ کنید . در مورد سوال keepalive هم سرور اول‌ ایران شماره یک میشه و شماره چهار سرور چهارم ایران .
> > 
> > 
> > اها من الان ی سرور جدید هم ساختم تانلش با خارج برقرار نمیشه نمیدونم باید چیکار کنم بعید میدونم اشتباهی هم انجام بدم
> 
> پس بهتره یک بار دیگه تمام سرور هارو پاک کنید و سریع . کانفیگ کنید . دفعه بعد قطع شد همین کارو بکنید چون هر سرور جداگانه وارد سرور لود بالانس خواهد شد
این کار رو فقط داخل سرور خارج انجام بدم کافیه؟

**Comment by Mehranhich** [comment]
> > > یعنی چی ؟ اون موردی که می‌پرسه فقط برای keepalive هست و داخل این روش چون همه سرور ها داخل لود بالانس میرن ، نیازی به مشخص کردن کانفیگ های جداگانه ندارد. شما فرض رو بر این بگیرید که پینگ بین آی‌پی ها رو خودتون اوکی میکنید . شما یک بار خارج رو وارد میکنید . بعد هر تعداد ایران دارید رو با کانفیگ ایران وارد میکنید . حالا نوبت پینگ هست . خودتون یک سرویس پینگ بین سرور خارج و سرور ایران مربوطه ایجاد کنید. اصلا نیازی نیست دوباره سرور خارج و ایران ها رو کانفیگ کنید . در مورد سوال keepalive هم سرور اول‌ ایران شماره یک میشه و شماره چهار سرور چهارم ایران .
> > 
> > 
> > اها من الان ی سرور جدید هم ساختم تانلش با خارج برقرار نمیشه نمیدونم باید چیکار کنم بعید میدونم اشتباهی هم انجام بدم
> 
> پس بهتره یک بار دیگه تمام سرور هارو پاک کنید و سریع . کانفیگ کنید . دفعه بعد قطع شد همین کارو بکنید چون هر سرور جداگانه وارد سرور لود بالانس خواهد شد

این کار رو فقط داخل خارج انجام بدم کافیه؟
ادیت : فقط خارج حذف کردم ب همه پینگ داد جز همون

**Comment by Azumi67** [comment]
> > > > یعنی چی ؟ اون موردی که می‌پرسه فقط برای keepalive هست و داخل این روش چون همه سرور ها داخل لود بالانس میرن ، نیازی به مشخص کردن کانفیگ های جداگانه ندارد. شما فرض رو بر این بگیرید که پینگ بین آی‌پی ها رو خودتون اوکی میکنید . شما یک بار خارج رو وارد میکنید . بعد هر تعداد ایران دارید رو با کانفیگ ایران وارد میکنید . حالا نوبت پینگ هست . خودتون یک سرویس پینگ بین سرور خارج و سرور ایران مربوطه ایجاد کنید. اصلا نیازی نیست دوباره سرور خارج و ایران ها رو کانفیگ کنید . در مورد سوال keepalive هم سرور اول‌ ایران شماره یک میشه و شماره چهار سرور چهارم ایران .
> > > 
> > > 
> > > اها من الان ی سرور جدید هم ساختم تانلش با خارج برقرار نمیشه نمیدونم باید چیکار کنم بعید میدونم اشتباهی هم انجام بدم
> > 
> > 
> > پس بهتره یک بار دیگه تمام سرور هارو پاک کنید و سریع . کانفیگ کنید . دفعه بعد قطع شد همین کارو بکنید چون هر سرور جداگانه وارد سرور لود بالانس خواهد شد
> 
> این کار رو فقط داخل خارج انجام بدم کافیه؟ ادیت : فقط خارج حذف کردم ب همه پینگ داد جز همون

اون سرور رو با روش دیگه به خارج کانفیگ کنید

**Comment by Mehranhich** [comment]
> > > > > یعنی چی ؟ اون موردی که می‌پرسه فقط برای keepalive هست و داخل این روش چون همه سرور ها داخل لود بالانس میرن ، نیازی به مشخص کردن کانفیگ های جداگانه ندارد. شما فرض رو بر این بگیرید که پینگ بین آی‌پی ها رو خودتون اوکی میکنید . شما یک بار خارج رو وارد میکنید . بعد هر تعداد ایران دارید رو با کانفیگ ایران وارد میکنید . حالا نوبت پینگ هست . خودتون یک سرویس پینگ بین سرور خارج و سرور ایران مربوطه ایجاد کنید. اصلا نیازی نیست دوباره سرور خارج و ایران ها رو کانفیگ کنید . در مورد سوال keepalive هم سرور اول‌ ایران شماره یک میشه و شماره چهار سرور چهارم ایران .
> > > > 
> > > > 
> > > > اها من الان ی سرور جدید هم ساختم تانلش با خارج برقرار نمیشه نمیدونم باید چیکار کنم بعید میدونم اشتباهی هم انجام بدم
> > > 
> > > 
> > > پس بهتره یک بار دیگه تمام سرور هارو پاک کنید و سریع . کانفیگ کنید . دفعه بعد قطع شد همین کارو بکنید چون هر سرور جداگانه وارد سرور لود بالانس خواهد شد
> > 
> > 
> > این کار رو فقط داخل خارج انجام بدم کافیه؟ ادیت : فقط خارج حذف کردم ب همه پینگ داد جز همون
> 
> اون سرور رو با روش دیگه به خارج کانفیگ کنید

با همون سرور های قبلی سینگل 6 ب 4زدم خارج رو اول بعد ایران رو ب هون لوکال پینگ داد و حل شد

**Comment by Mehranhich** [comment]
همین الان کلا سرور های ایران ک anycast زدم از دسترس خارج شدن ولی اون ک سینگل زدم پینگ داره

**Comment by Azumi67** [comment]
> همین الان کلا سرور های ایران ک anycast زدم از دسترس خارج شدن ولی اون ک سینگل زدم پینگ داره ادیت: بعد 2دقیقه پینگ نداشتن دوباره خودشون بالا اومدن دیروز این حالت 3 4باری پیش اومد ولی چون پشت سیستم نبودم نمیدونستم چخبره

ممکنه اختلال داشته باشد . روش که مشکلی نداره،‌ مشکل اختلال سرور های ایران هست .

**Comment by Mehranhich** [comment]
> > همین الان کلا سرور های ایران ک anycast زدم از دسترس خارج شدن ولی اون ک سینگل زدم پینگ داره ادیت: بعد 2دقیقه پینگ نداشتن دوباره خودشون بالا اومدن دیروز این حالت 3 4باری پیش اومد ولی چون پشت سیستم نبودم نمیدونستم چخبره
> 
> ممکنه اختلال داشته باشد . روش که مشکلی نداره،‌ مشکل اختلال سرور های ایران هست .

همه ای پی ها از یک رنج
سینگل 6 ب 4 ک زدم پینگ داشتا

**Comment by Mehranhich** [comment]
برای تانل anycast نیازه ک ipv4 سرور خارج تمیز باشه و از سرور های ایران بشه پینگ گرفت یا اهمیت نداره؟

**Comment by Azumi67** [comment]
شما سرورتون با این روش ها انگار مشکل داره . یک بار isatap تست کنید و هم چنین gre6tap . بعدا لوکال‌ وایرگارد هم اضافه شد میتونید تست کنید .
