### ISSUE TITLE
مشکل در نصب کد ipipv2.py در یکی از سرورها

### ISSUE THREAD

**Issue by mehrdadashna** [Azumi67/6TO4-GRE-IPIP-SIT#73]
علت اینکه در فایل ipipv2.py برای لاین 126 خطای زیر میده به خاطر چی میتونه باشه؟

  File "/root/ipipv2.py", line 126
    <title>6TO4-GRE-IPIP-SIT/ipipv2.py at main · Azumi67/6TO4-GRE-IPIP-SIT · GitHub</title>
           ^
SyntaxError: invalid decimal literal

البته در سرور ایران این خطارو نمیده.
منظورش این هست که در کد پایتون نباید تگ html باشه؟
البته بنده وارد نیستم و با جستجو در اینترنت یک چیزهایی دیدم.
و متاسفانه امکان پیکربندی مجدد ندارم.

**Comment by Azumi67** [comment]
شما این هم تست کنید 
`bash -c "$(curl -fsSL https://raw.githubusercontent.com/Azumi67/6TO4-GRE-IPIP-SIT/main/ubuntu24.sh)"`
