### ISSUE TITLE
ادیت تک سرور

### ISSUE THREAD

**Issue by Mohammadaminsdr** [Azumi67/6TO4-GRE-IPIP-SIT#74]
سلام وقتتون بخیر و خسته نباشید 

این روش ادیت سرور به تک سرور ها اضافه نمیشه ؟

**Comment by Azumi67** [comment]
سلام‌. ویرایش تک سرور به دلیل اینکه تفاوتی در نتیجه ایجاد نمی‌شود، اضافه نشده است . چون شما برای تک سرور نیازی نیست که جداگانه حذف و ویرایش انجام دهید .
اما ویرایش کاملتری هم برای تک سرور و مولتی در راه است . زمان میبرد تا کاملش کنم .
