### ISSUE TITLE
مشکل gre6tab

### ISSUE THREAD

**Issue by Mehranhich** [Azumi67/6TO4-GRE-IPIP-SIT#75]
سلام چرا موقع تانل کردن بعد اینکه ipv6 native های خارج و ایران رو داخل سرور خارج میزنم ارور address rechable میده بعد اینکه تانل ساخته میشه
فایروال سرور هم خاموشه
ادرس ipv6 ها هم درست میزنم و اینکه از هردو سرور v6ها ب هم پینگ هم میدن
![20240726_093655](https://github.com/user-attachments/assets/ae42c3dc-c34b-439f-ba94-dba746e41bbb)

**Comment by Azumi67** [comment]
سلام. تست کردم و مشکلی نداشت. اگر داخل اسکریپت پینگ نداد . بیرون از ان پینگ بگیرید
