### ISSUE TITLE
مشکل با vxlan

### ISSUE THREAD

**Issue by farshidpg** [Azumi67/6TO4-GRE-IPIP-SIT#76]
سلام خسته نباشید ، بنده مشکلی دارم با vxlan  ، همه حالت های vxlan چه با ریست تایمر و چه بدون ریست تایمر  حالتی پیش میاره که هر یک دقیقه کانکت ، ریکانکت اتفاق میوفته ، من برای open و cisco و استفاده شخصی از vxlan ipsec و  vxlan FDB تست کردم 
 اتفاقی که میوفته به این شکل هستش که اتصال در برنامه open vpn یا cisco  کاملا برقراره بدون مشکل و اینترنت به صورت کلی قطع نمیشه اما در برنامه هایی مثل ریموت دسکتاپ یا RDP  دقیقا هر یک دقیقه ریکانکت  میشه ، همچنین اگر اتصال SSH و ترمینالی روی سیستم داشته باشید دقیقا  سر یک دقیقه اون هم ریکانکت میشه و عملا کانکشن ssh لاست میشه من ابتدا فکر کردم از reset تایمر هست اما ابتدا ریست تایمر رو حذف کردم و در مرحله بعدی کل کانفیگ رو حذف کردم و مجدد کانفیگ کردم اما همچنان مشکل برقراره و عملا برای انجام کار هایی مثل ارتباط با SSH یا ریموت دسکتاپ مشکل ایجاد میکنه چرا که این کانکت و ریکانکت مشکل ساز هستش مخصوصا زمانی که با SSH دارید کار میکنید یهو میبینید دیگه ترمینال آپدیت نمیشه ،  هر دو برنامه open vpn و cisco همین مشکل رو دارند در صورتی که با همین سرور ها و روش تانل متفاوت چنین اتفاقی نمیوفته  . دلیل این قطعی چی میتونه باشه ؟

ممنونم

**Comment by Azumi67** [comment]
سلام. من هم ovpn با vxlan استفاده کردم و هم ترکیب local tun vxlan استفاده کردم و چنین مشکلی نداشتم و مدت طولانی استفاده کردم . شما باید دو کار کنید . مورد اول اینکه باید یک لپ تایم کوما‌ نصب کنید و از ندادن پکت لاس و نبود قطعی ارتباط اطمینان حاصل کنید و مورد دوم باید استاتوس تانل اصلی یا پورت فوروارد رو بررسی کنید و ببینید که مشکل از اونجا نباشد .

**Comment by farshidpg** [comment]
امکان داره از mtu باشه ؟ من روی حالت اتوماتیک و همین طور برای هر دو سرور مقدار 1422  که بالا ترین مقدار ممکن بود ست  کردم ولی همچنان مشکل وجود داشت

**Comment by farshidpg** [comment]
همه موارد رو تست کردم همچنین آی پی ها هم عوض کردم مجدد با تانل های دیگه تست کردم و مشکلی نبود  اما با ریموت دسکتاپ این مشکل هست حتی همزمان پیگ لوکال هر دو سرور رو با هم مانیتور کردم و دقیقا زمانی که ریموت دسکتاپ ریکانکت میشه هر دو سرور ایران و خارج بدون مشکل به هم پینگ دارند و حتی یک فایل هم زدم دانلود بشه و توی، دانلود اون هم مشکلی نبود  اگر تمایل داشته باشید میتونیم دسترسی هر دو سرور ایران و خارج رو و کانفیگ رو براتون بفرستم . خودتون هم تست کنید

**Comment by farshidpg** [comment]
مجدد من بررسی کردم فقط کانکشن های سوکت قطع میشند . حالا میخواد وب سوکت تحت وب باشه یا هر اپلیکیشن دیگه ای گه با سوکت کار میکنند . اتصال سوکت برای یک لحظه به صورت لوپ  قطع میشه

**Comment by Azumi67** [comment]
جالبه .من خودم شخصا چنین مشکلی تجربه نکردم . لطفاً با geneve تست کنید و ببینید باز هم همین هست یا خیر.

**Comment by farshidpg** [comment]
با تانل های دیگه مشکلی ندارم ، اما دقیقا بفرمایید با کدام مدل تانل اسکریپت خودتون که مد نظرتونه کانفیگ و تست کنم روی همین سرور ها نتیجه رو اعلام کنم ، اگر تمایل داشتید میتونم نمونه کانفیگ open vpn و cisco  و همین طور دسترسی سرور ها رو بفرستم براتون . چون من چند اینترنت و سیستم عامل مختلف تست گرفتم فرقی نکرد

**Comment by Azumi67** [comment]
> با تانل های دیگه مشکلی ندارم ، اما دقیقا بفرمایید با کدام مدل تانل اسکریپت خودتون که مد نظرتونه کانفیگ و تست کنم روی همین سرور ها نتیجه رو اعلام کنم ، اگر تمایل داشتید میتونم نمونه کانفیگ open vpn و cisco و همین طور دسترسی سرور ها رو بفرستم براتون . چون من چند اینترنت و سیستم عامل مختلف تست گرفتم فرقی نکرد

راستش من در حال حاضر کمی بیمار هستم و توانایی بررسی بیشتر رو ندارم . شما با geneve داخل اسکریپت تست بفرمایید و ببینید آیا با آن تانل هم همین هست یا خیر

**Comment by farshidpg** [comment]
با این ۲ متد تست شد

روش اول 
3) Geneve UDP -> Method 2[Route]

روش دوم
4) Geneve + IPsec -> Geneve + IPsec


با روش اول مشکلی وجود نداشت اما با روش دوم دقیقا مشابه vxlan مشکل قطعی کانکشن های سوکت  از سمت کاربر وجود داشت ، فکر میکنم هر چی هست از ipsec باشه چرا که vxlan هم دقیقا با ipsec کانفیگ کرده بودم

**Comment by Azumi67** [comment]
پس شما بدون IPsec استفاده کنید و اگر میخواهید IPsec استفاده کنید از تایمر دو دقیقه برای IPsec استفاده کنید .

**Comment by Azumi67** [comment]
بعدا روش وایرگارد و l2tpv3 هم قرار می‌دهم که میتونید آنها هم تست بفرمایید .

**Comment by farshidpg** [comment]
تایمر دو دقیقه ای یعنی هر دو دقیقه تانل قطع میشه ؟ مثل همین الان که هر ۱ دقیقه قطع میشه ؟ چون من تایمر ها رو چند مرتبه برای تست که کلا ست نکردم و هر بار هم که ست میکنیم برای حفظ پایداری اتصال روی ۶ ساعت قرار دادم 

 این مشکل از چیه ؟ چون شما گفتید خودتون این مشکل رو ندارید

**Comment by Azumi67** [comment]
> تایمر دو دقیقه ای یعنی هر دو دقیقه تانل قطع میشه ؟ مثل همین الان که هر ۱ دقیقه قطع میشه ؟ چون من تایمر ها رو چند مرتبه برای تست که کلا ست نکردم و هر بار هم که ست میکنیم برای حفظ پایداری اتصال روی ۶ ساعت قرار دادم
> 
> این مشکل از چیه ؟ چون شما گفتید خودتون این مشکل رو ندارید

 باعث قطعی تانل نمیشه . باید شما‌ اول‌ ببینید که پینگ بین دو سرور در زمان قطعی شما هم قطع می‌شود یا خیر . چون اگر پینگ قطع نشود  ربطی به IPsec ندارد . تنها وقتی میتوانیم بگیم به IPsec ربط دارد که پینگ هم برود . شما یک بار تانل‌ اصلی پس از تانل 6to4 را تغییر بدید و بر روی پورت متفاوتی تست کنید . من خودم بر روی پورت 1180 udp استفاده میکنم . تا بررسی دقیق تری انجام ندهید نمیشود کامل مشکل را پیدا کرد .

**Comment by farshidpg** [comment]
پیک پابلیک و لوکال هر ۲ سرور قطع نمیشود حتی نوسان هم ندارد . تانل رو روی پورت 5514 هم تست کردم من از روژن ipv4 برای vxlan + ipsec استفاده میکنم و open و cisco هم به صورت TCP  روی پورت های مخلتلف تست کردم .

**Comment by Azumi67** [comment]
من tcp استفاده نمیکنم . به هر حال پس از اضافه شدن ویرایش لوکال آی‌پی، روش های جدید هم میتونید تست کنید و بهم اطلاع بدید. روش isatap هم تست کنید .

**Comment by farshidpg** [comment]
ممنونم تست میکنم اطلاع میدم ، در حال حاضر سرور شخصی که برای استفاده شخصی خودم استفاده میکردم برای اندروید استدیو و .. با ۴۰ گیگ ترافیک محدود شد با روش vxlan ipsec p2p و waterwall اما آی پی خارج و ایران هر دو پینگ پابلیک دارند . در هر صورت مجدد روش های دیگه رو تست میکنم و اطلاع میدم ، اما محدودیت ها به صورتی شده که با آپدیت یک اندروید استدیو و حجم ۱۰-۲۰ گیگ دانلود محدودیت ایجاد میکنند در هر صورت ممنونم از شما

**Comment by farshidpg** [comment]
این مشکل وقتی با ipv4 لوکال که تانل میزنم وجود داره و احتمالا اختلالی روی ipv4 هست ، جدیدا با لوکال 6 میزنم و چنین مشکی نداشتند هیچ کدوم از روش ها  ظاهرا مشکل از ipv4 و اعمال محدودیت ها هستش چرا که خیلی زود هم محدود یا فیلتر میشند ، اما سوال من اینه با در نظر گرفتن شرایط عادی و پایدار یک شبکه آزاد ، و یکسان بودن منابع سرور . کدام یکی از تانل ها سرعت و کیفیت و پایداری بالاتری دارد ؟ فارق از 6 یا 4 بودن آنها و فرض عدم وجود هیچ محدودیتی

vxlan p2p 
vxlan FDB 
isatap
Geneve
GRE

چون با توجه به تست هایی که داشتم با شرایط فعلی تقریبا روی سرور من همه جواب بودند و برای اطلاعات خودم این سوال رو مطرح کردم ، ممنونم

**Comment by Azumi67** [comment]
سلام. من خودم یه مدت طولانی از geneve استفاده کردم
