### ISSUE TITLE
GRE6 Multiple Servers  اتصال به بیش از 3 سرور خارج در روش

### ISSUE THREAD

**Issue by mehdininpo** [Azumi67/6TO4-GRE-IPIP-SIT#8]
اول یه تشکر کنم بابت این اسکریپت فوق‌العاده
من تعداد سرورهای خارج م بیشتر از ۳ تا هست 
با این روش شما سرور های خارج رو به ایران متصل میکنم و بعد از طریق nginx تانل رو برقرار میکنم.
میخواستم ببینم چطوری میتونم بیشتر از ۳ سرور خارج رو با روش GRE6 به ایران وصل کنم و روی سرور ایران همگی پینگ بدن.

**Comment by Azumi67** [comment]
سلام. خودم دارم به تعداد سرور ها می افزایم. شاید امروز آپدیت بشه .

**Comment by mehdininpo** [comment]
بسیار عالی اگر تا ۲۰ تا امکان افزودن باشه عالی میشه.
احیانا اگر هم افزودن تعداد زیاد داخل اسکریپت سخته روشی رو بگین که خودم بتونم به صورت دستی اضافه کنم.
و اگر بشه که اسکریپت کلا تعداد سرور خارج رو بپرسه و بر اساس اون تعداد اضافه کنه و محدودیتی نباشه که خیلی عالی میشه.

**Comment by Azumi67** [comment]
20 تا زیاده و من چنین کاری نمیکنم . شما دستورات کامند ها رو برای هر سرور انجام بدید و سرویس هم بسازید .

**Comment by mehdininpo** [comment]
> 20 تا زیاده و من چنین کاری نمیکنم . شما دستورات کامند ها رو برای هر سرور انجام بدید و سرویس هم بسازید .

چطوری این کارو بکنم لطفا راهنمایی کنید.
خیلی برام مهمه بتونم این کارو بکنم.

**Comment by mehdininpo** [comment]
مهندس جان یه راهنمایی می کنین?
