### ISSUE TITLE
 6to4  قطعی سرور خارج  

### ISSUE THREAD

**Issue by pouriasharifzad** [Azumi67/6TO4-GRE-IPIP-SIT#81]
سلام من از تانل 6به4 یه ایران 10 خارج استفاده میکنم

بعضی اوقات اتصال یکی دوتا از سرورا قطع میشه ولی با یه ریبوت سرور خارج مجدد برقرار میشه . 

جایی لاگ هست که بشه چک کرد مشکل از کجاست؟

**Comment by Azumi67** [comment]
سلام شما احتمالا اختلال سرور دارید . اگر اختلال نباشه بهتره بر روی سرور هاتون یک Kuma اپ تایم رو نصب کنید تا ببینید در چه بازه زمانی این اتفاق میوفته . خیلی ها با روش sit مشکل دارند و یک موضوع نرمالی شده یا اصلا ممکنه اگر از پورت فوروارد مولتی پورت استفاده میکنید باشه . اگر بدون IPsec هست که هیچی اما اگر با IPsec هست ممکنه از ریست تایمر باشد . دلایلی زیادی می‌تونه داشته باشه . سرویس های keepalive هم میتونید بررسی کنید که همون کار Kuma uptime رو انجام میدهد .
