### ISSUE TITLE
پیشنهاد

### ISSUE THREAD

**Issue by Mohammadaminsdr** [Azumi67/6TO4-GRE-IPIP-SIT#82]
سلام وقت بخیر خسته نباشید یه پیشنهاد داشتم این روش های دالخ اسکرپیت بر بستر ipv4 هستش و اگه امکانش باشه بر بستر ipv6 هم اضافه کنید که اکسسی کمتر باشه :) 

ممنون از اینکه هستید

**Comment by Azumi67** [comment]
سلام مرسی. منظورتون ارتباط اول با ipv6 هست ؟ چندین نمونه از روش ها ارتباط اولشون با آی‌پی ۶ می‌باشد . 
به زودی شاید آخر هفته بتونم وایرگارد و چند ترکیب هم بیاورم که در یکی از روش ها ارتباط اول با آی‌پی ۶ می‌باشد .

**Comment by Mohammadaminsdr** [comment]
ممنون از رحمتی که میکشین و اینکه با توجه به تست خودتون رو سرور های ایران دیگه کدوم روش مناسبه ؟ پایدار و سرعت خوبی داره ؟ البته باید تست کرد تا متوجه شد ولی خب نظرتون رو بگین حتما :)
