### ISSUE TITLE
درخواست و پیشنهاد

### ISSUE THREAD

**Issue by arash0921** [Azumi67/6TO4-GRE-IPIP-SIT#83]
سلام اول این که ممنونم ازت خیلی خفنی.اکانش هست روش vxlan روی مالتی سرور اضافه شه؟

**Comment by Azumi67** [comment]
سلام مرسی. بله پس از اینکه وایرگارد و ترکیباتش کامل بشه، اونم میشه انجام داد . من چون زمان کمی برای کار کردن بر روی پروژه ها دارم، معمولا چند هفته طول می‌کشه چون کسی نیست که در این کد ها کمکی کند.

**Comment by arash0921** [comment]
ممنونم واقا خسته نباشی.پس ما منتظریم🙏
