### ISSUE TITLE
مشکل در سرور خارج

### ISSUE THREAD

**Issue by fsh230** [Azumi67/6TO4-GRE-IPIP-SIT#84]
سلام وقت بخیر اول از شما تشکر می کنم بابت این سرویس خوب تون
من یه مشکلی توی سرور خارج دارم عکسش رو می ذارم اینجا براتون این خطا برای چیه تانل gre ip6  جواب نگرفتم
![Screenshot 2024-08-14 172309](https://github.com/user-attachments/assets/844f1191-09fd-4238-af8d-cfe8f15dc04c)

مرسی

**Comment by Azumi67** [comment]
سلام. دلیل پینگ ندادن می‌تونه متفاوت باشد. مثلا ممکنه سرور خارج شما در سرور ایران شما اختلال داشته باشد و باعث بشود که ارتباط اول که بر پایه sit است برای شما کار نکند و پینگ ندهد . سناریو دوم ممکن است در اسکریپت پینگ ندهد و وقتی خودتان به صورت manual پینگ بگیرید، پینگ بدهد . شما یک بار از طریق edit local، تلاش برای تغییر لوکال‌ آی‌پی بکنید و مطمئن بشوید که پرایوت آی‌پی ها را نبسته آید و هم چنین روی یک سرور خارج دیگر تست نمایید .

**Comment by fsh230** [comment]
سلام مطمئن هستم که private ip رو نبستم 
میخوام روی یک سرور خارج دیگه تست کنم
