### ISSUE TITLE
حذف شدن آیپی 6 لوکال پس از ریبوت سرور مجازی

### ISSUE THREAD

**Issue by AsanFillter** [Azumi67/6TO4-GRE-IPIP-SIT#85]
درود وقتت بخیر باشه، یک مشکلی رو بنده بررسی کردم روی تانل 6TO4 [Anycasnt] به صورت تک سرور بعد از ریستارت شدن سرور مجازی فرقی نمیکنه ایران یا خارج آیپی لوکالی که ساخته شده به طور کامل حذف میشه و ارتباط از بین میره.
نیاز هست که دوباره تمام مراحل رو پیش رفت تا کانکشن مجدد برقرار بشه.

**Comment by AsanFillter** [comment]
کرون جاب رو باید تنظیم کرد یا خودش به صورت خودکار تنظیم میشه؟ اگر که باید تنظیم کرد از کدوم بخش
خوشحال میشم راهنمایی بفرمایید سپاسگزارم .

**Comment by Azumi67** [comment]
کرون جاب خودش اتوماتیک ست می‌شود. شما باید دقت کنید و ببینید که چرا کرون جاب برای شما پاک شده است . دلیل اون رو بیابید چون اسکریپت کرون جاب را ست میکند .
