### ISSUE TITLE
مشکل در یک دیتا سنتر خاص

### ISSUE THREAD

**Issue by phframe** [Azumi67/6TO4-GRE-IPIP-SIT#86]
سلام من ازومی رو رو همه دیتا سنتر ها تست کردم اوکی بوده (سرور خارج) ولی چن وقته رو یه دیتا سنتر خارجی هر کار میکنم وصل نمیشه جالبیش اینه پینگ میده با ha proxy تانلش کردم اونم میگه وصله اروری نمیده ولی در اخر کار نمیکنه اینم بگم همه مواردو تست کردم مشکل از سرور خارجه حالا نه فقط اون سرور از اون دیتا سنتر همه کشوراش یا ابونتو ورژن مختلف تست کردم تانلیم که میزنم gre6 یه ایرن یه خارج
![image](https://github.com/user-attachments/assets/e5528c87-627d-4dbe-8418-eb72a0883544)
![image](https://github.com/user-attachments/assets/5f2ede54-3a39-4125-9bd6-2d426049171a)

**Comment by Azumi67** [comment]
سلام. روش تانل رو عوض کنید و با پورت فوروارد های دیگری هم تست نمایید . از فوروارد شدن ایپی 4 و 6 هم اطمینان حاصل کنید.
