### ISSUE TITLE
کدام روش با ای فیلتر کار میده؟

### ISSUE THREAD

**Issue by Mehranhich** [Azumi67/6TO4-GRE-IPIP-SIT#87]
درود خسته نباشید کدوم روش رو بزنم ک وقتی ipv4 فیلتر هم شد جواب بده؟

**Comment by Azumi67** [comment]
سلام مرسی. من مثل قبل دسترسی به سرور های مختلف ندارم و طبیعتاً نمیتونم این موضوع هم تست کنم. باید خودتون تست کنید . الان شرایط خیلی با قبل فرق دارد.

**Comment by Mehranhich** [comment]
> سلام مرسی. من مثل قبل دسترسی به سرور های مختلف ندارم و طبیعتاً نمیتونم این موضوع هم تست کنم. باید خودتون تست کنید . الان شرایط خیلی با قبل فرق دارد.

شما میدونید ک کدوم روش کلا ب ipv4 سرور نیاز نداره؟
خب قبلا کدوم روش بود ک جواب میداد؟
الان کلا ipv4 پینگ نده تانل هم قطع میشه

**Comment by Azumi67** [comment]
> > سلام مرسی. من مثل قبل دسترسی به سرور های مختلف ندارم و طبیعتاً نمیتونم این موضوع هم تست کنم. باید خودتون تست کنید . الان شرایط خیلی با قبل فرق دارد.
> 
> شما میدونید ک کدوم روش کلا ب ipv4 سرور نیاز نداره؟ خب قبلا کدوم روش بود ک جواب میداد؟ الان کلا ipv4 پینگ نده تانل هم قطع میشه

با ایپی native هم تست کردید ؟ باید صبر کنید تعداد روش ها زیادتر شود. مثلا روش های dns icmp و تانل های دیگر که دارم روشون کار میکنم .

**Comment by Mehranhich** [comment]
> > > سلام مرسی. من مثل قبل دسترسی به سرور های مختلف ندارم و طبیعتاً نمیتونم این موضوع هم تست کنم. باید خودتون تست کنید . الان شرایط خیلی با قبل فرق دارد.
> > 
> > 
> > شما میدونید ک کدوم روش کلا ب ipv4 سرور نیاز نداره؟ خب قبلا کدوم روش بود ک جواب میداد؟ الان کلا ipv4 پینگ نده تانل هم قطع میشه
> 
> با ایپی native هم تست کردید ؟ باید صبر کنید تعداد روش ها زیادتر شود. مثلا روش های dns icmp و تانل های دیگر که دارم روشون کار میکنم .

نه کدوم شماره میشه؟

**Comment by Azumi67** [comment]
اون هایی که ارتباط اولشون با native ipv6 است . مثلا gre6tap ها

**Comment by Mehranhich** [comment]
geneve+native زدم اوکیه با ای پی فیلتر ممنون
