### ISSUE TITLE
مشکل پینگ نگرفتن ایپی های لوکال 

### ISSUE THREAD

**Issue by H2mz** [Azumi67/6TO4-GRE-IPIP-SIT#88]
من تمام روش ها ور تست کردم متاسفانه ایپی های که ساخته میشه بهم پنگ ندارن 

موارد که تو اموزش ها گفتن کامل رعایت شده 

سور های خارج و ایران هم پینگ ورژن4 دارن هم پینگ ورژن6

**Comment by Azumi67** [comment]
روش ها که مدت طولانی استفاده و تست شده و کار میکند . ممکنه مشکل شما بسته بودن پرایوت آی‌پی ها در سرور مربوطه باشد . باید این موضوع را بررسی کنید . در خود اسکریپت هم میتوانید از قسمت edit local اقدام به تغییر پرایوت آی‌پی ها و تست دوباره نمایید .
