### ISSUE TITLE
ارور سینتکس هنگام اجرا

### ISSUE THREAD

**Issue by mohamadaz** [Azumi67/6TO4-GRE-IPIP-SIT#89]
سلام من اوبونتو 24 دارم قبلا هم نصب داشتم اسکریپت رو الان میخوام بازش کنم این ارورو میده:
/root/ubuntu24.py:140: SyntaxWarning: invalid escape sequence '\_'

**Comment by Azumi67** [comment]
سلام من روی ubuntu24 دوباره تست کردم و مشکلی نبوذ. اون خطا توی نسخه قبلی هم میومد. باید بعد از اون خطا منو رو نشون بده.

**Comment by mohamadaz** [comment]
بعد از خطا kill میده متاسفانه

**Comment by Azumi67** [comment]
خطای kill رو بفرستید یا سرور رو در صورت امکان به ایمیل من بفرستید تا بعدا نگاه کنم

**Comment by mohamadaz** [comment]
فقط مینویسه killed

**Comment by Azumi67** [comment]
سلام. دوباره تست کنید .
