### ISSUE TITLE
نحوه ساخت کانفیگ

### ISSUE THREAD

**Issue by Sharevex** [Azumi67/6TO4-GRE-IPIP-SIT#9]
سلام وقتتون بخیر ، بعد از اتمام تانلینگ چه نوع کانفیگی بهتره بسازیم و آیا باید روی هر دو تا سرور ( خارج و داخل ) پنل نصب باشه واسه ساختن کانفیگ ؟ ممنون میشم راهنمایی بفرمایین

**Comment by Azumi67** [comment]
سلام. اون دیگه بستگی به شما داره. یکی با ریالیتی انجام میده یکی‌ با ovpn . شما باید ببینید کدوم به کارتون میاد .

**Comment by Sharevex** [comment]
درسته متوجه هستم ، منظورم این هستش که آیا باید روی هر دو تا سرور پنل نصب بشه(من xray استفاده میکنم) ؟ یا اینکه رو سرور خارج نصب شه فقط . به جای آیپی سرور خارج ، آیپی سرور ایران قرار داده بشه ؟

**Comment by Azumi67** [comment]
اگر از از هسته xray استفاده میکنید . برای doko ایران هم نیازه . و برای outbound هم باید روی سرور ایران نصب باشه . اگر تانل های دیگری هست ، فقط کافیه سرور خارج ، پنل نصب باشه .

**Comment by Sharevex** [comment]
سپاس بیکران از محبتتون ، لطف کردین 
امیدوارم همواره بتونین به بهترین ها برسین
