### ISSUE TITLE
مصرف ترافیک

### ISSUE THREAD

**Issue by AsanFillter** [Azumi67/6TO4-GRE-IPIP-SIT#90]
درود وقت بخیر ، یه سوالی داشتم خدمتت اینه که ترافیک کدوم روش از تانل هایی که نوشتی دو برابر نیست؟ چون الان anycast رو اجرا کردیم همه چی 2 برابر شده حتی دانلود، سرور آپلودش رایگانه اما دانلودم دو برابر شده.
ممنون میشم راهنمایی کنی

**Comment by kalilovers** [comment]
> درود وقت بخیر ، یه سوالی داشتم خدمتت اینه که ترافیک کدوم روش از تانل هایی که نوشتی دو برابر نیست؟ چون الان anycast رو اجرا کردیم همه چی 2 برابر شده حتی دانلود، سرور آپلودش رایگانه اما دانلودم دو برابر شده. ممنون میشم راهنمایی کنی

سلام مصرف دوبرابر نیستش درضمن اون متدی هم که میفرمایید اتفاقا مصرف خاصی هم نداره حتی نصف متد های ترکیبی توی اسکریپت هم نیست مصرفش (اونا هم مصرف محسوسی ندارن) اینکه دوبرابر میفرمایید داخل پنل به اون صورت نشون میده بخاطر اینترفیس یا کارت شبکه های مجازی متفاوت هستش که اونطوری محاسبه میشه توی پنل (مثلا دانلود دوبربر آپلود نمایش داده میشه اونم فقط قسمت محاسبه کلی پنل نه کاربران) وگرنه یک به یک هست . مشکلی نیست

**Comment by AsanFillter** [comment]
درسته ممنونم ازت 🙏🌹
