### ISSUE TITLE
ارور killed

### ISSUE THREAD

**Issue by pilot-code** [Azumi67/6TO4-GRE-IPIP-SIT#91]
با سلام 
ضمن تشکر از آزومی بابت اسکریپت 

یه مشکلی که دارم میخوام اسکریپت رو اجرا کنم با خطای killed مواجه میشم تمامی پسش نیاز هارو نصب داشتم و این مشکل قبلا نداشتم روی همین سرور اسکریپت رو اجرا کردم دیروز ولی الان خطا میگیرم

**Comment by pilot-code** [comment]
![IMG_4800](https://github.com/user-attachments/assets/a0d18850-b695-4b6a-8c33-f620e7fe8a43)

**Comment by Azumi67** [comment]
سلام. اینم تست کنید 
`bash -c "$(curl -fsSL https://raw.githubusercontent.com/Azumi67/6TO4-GRE-IPIP-SIT/main/ubuntu24.sh)"`
