### ISSUE TITLE
Address unreachable  مربوط به چی میشه سرور بسته این حالت یا؟؟

### ISSUE THREAD

**Issue by jadopcb** [Azumi67/6TO4-GRE-IPIP-SIT#92]
ping 2002:401b::1
PING 2002:401b::1(2002:401b::1) 56 data bytes
From 2002:401b::2 icmp_seq=1 Destination unreachable: Address unreachable
From 2002:401b::2 icmp_seq=2 Destination unreachable: Address unreachable
From 2002:401b::2 icmp_seq=3 Destination unreachable: Address unreachable
From 2002:401b::2 icmp_seq=4 Destination unreachable: Address unreachable
From 2002:401b::2 icmp_seq=5 Destination unreachable: Address unreachable
^C
--- 2002:401b::1 ping statistics ---
5 packets transmitted, 0 received, +5 errors, 100% packet loss, time 4096ms

ip6  هر کدوم روی سرور خودشون پینگ دارن

من سرور دیگه دارم مشکلی ندارم
 اما سرور از ایرانسل دارم
 این ارتباط برقرار نمیشه
مشکل بخ خاطر سرور این حالت بسته یا راهی داره؟؟؟

[10]KHAREJ [5]IRAN  Multiple Servers Menu

از این روش استفاده میکنم

ایا میشه به سرور خارج 1با روش مختلف وصل شد؟

به این سرور که الان جندتا سرور ایران وصله
 خارج 1یک سرور ایران با روش دیگه متصل کردبه همو سرور

**Comment by jadopcb** [comment]
root@irancell1:/home/ubuntu# netstat -rn
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         192.168.10.1    0.0.0.0         UG        0 0          0 ens3
8.8.4.4         192.168.10.1    255.255.255.255 UGH       0 0          0 ens3
8.8.8.8         192.168.10.1    255.255.255.255 UGH       0 0          0 ens3
169.254.169.254 192.168.10.2    255.255.255.255 UGH       0 0          0 ens3
192.168.10.0    0.0.0.0         255.255.255.0   U         0 0          0 ens3
192.168.10.1    0.0.0.0         255.255.255.255 UH        0 0          0 ens3
192.168.10.2    0.0.0.0         255.255.255.255 UH        0 0          0 ens3

**Comment by Azumi67** [comment]
سلام. دلیل های زیادی می‌تونه داشته باشه . یکی از دلایلش می‌تونه این باشه که اون روش بر روی سرور ایرانسل بسته باشه که باید از روش دیگری استفاده کنید. بله بر روی اون سرور به خصوص از روش دیگری استفاده کنید .
