### ISSUE TITLE
Private IP F1

### ISSUE THREAD

**Issue by The13east** [Azumi67/6TO4-GRE-IPIP-SIT#93]
سلام 
سوالی برام پیش اومده که توی تانل ها یه private ip وجود داره که توی multi server معلوم نیست کدومه ... 
ممکنه کمک کنید ؟
من برای مولتی 2 تا ایران دارم و یه خارج وقتی که 6t04 رو میزنم تانل تایم اوت زیادی داره و قطع میشه ولی توی سینگل سرور private ip عالی وصل میشه ولی نمیدونم مولتی کدوم گزینه هست

**Comment by Azumi67** [comment]
سلام . نام و روش پرایوت ایپی single با 6t04 مولتی یکسان است. میتوانید پرایوت ایپی سینگل را از طریق edit local برای 6to4 مولتی هم استفاده نمایید وگرنه روش ها یکی میباشد. اما 6to4 سینگل کمی فرق دارد.

**Comment by The13east** [comment]
الان گزینه 8 سینگل ها که private ip هست با 6t04 مولتی یکسانه ؟ دلیل اینکه من مولتی رو استفاده میکنم و تانل قطع و وصلی داره رو میدونید ؟  پینگ ای پی لوکال رو که میگیرم هر یه مدت میپره 
و گفتین که بعد از درست کردن سینگل میتونم ادیت کنم لوکال هارو و سرور بعدی رو اضافه کنم ؟

**Comment by Azumi67** [comment]
روش یکسانه اما شما میتوانید پرایوت آی‌پی مولتی رو با گزینه edit local به پرایوت آی‌پی single private تغییر دهید . قطعی و وصلی تانل برای این هست که اون سرور خارجی مربوطه در سرور ایران مشکل دارد یا سرور ایران شما از آن مدل سرور ها هست که نیاز به ربات ریکانفیگ دارد . یعنی به عبارتی هر دفعه که تانل شما قطع میشود باید ریکانفیگ انجام شود تا دوباره کار کند .
برای هر دو این موضوع در خود اسکریپت این گزینه ها قرار داده شده است . هم edit local و هم ریکانفیگ

**Comment by The13east** [comment]
فک کنم قطع شدن رو بد توضیح دادم 
در حالت سینگل سرور به خوبی کار میکنه و مشکلی نداره ولی موقعی مولتی میشه از هر دقیقه 40 ثانیه وصله و 20 ثانیه قطع ... 
دلیلش رو نمیدونم ولی اگر نیاز دارید خودتون بررسی کنید میتونم بهتون دسترسی بدم ببینید
