### ISSUE TITLE
کم نشدن حجم کانفیگ ها

### ISSUE THREAD

**Issue by mahdi14541380** [Azumi67/6TO4-GRE-IPIP-SIT#94]
سلام خسته نباشید من از روش 6TO4 مولتی سرور استفاده میکنم و تعداد افراد انلاین رو نشون نمیده و حتی حجمی که مصرف میکنن هم از کانفیگ کم نمیشه دلیلش برای چیه؟

**Comment by Azumi67** [comment]
سلام ربطی به روش ندارد و این مورد به پنل شما مربوط می‌باشد.
