### ISSUE TITLE
Wireguard Problem

### ISSUE THREAD

**Issue by mr-uranium** [Azumi67/6TO4-GRE-IPIP-SIT#95]
بعد از اجرای اسکریپت و متصل کردن دو تا سرور بهم از طریق وایرگارد، زمانی که سرور ها ریبوت میشن اتصال سرور های (Client Server) به سرور اصلی قطع میشه و ip های ساخته شده در تنظیمات شبکه حذف میشن. 
خلاصه بگم این ارتباط تا زمانی کار میکنه که سرور ها ریبوت نشن.
راه حل این مشکل چیه ؟؟؟

**Comment by Azumi67** [comment]
باید سرویسشون فعال شده باشه . نگاه میکنم اگر مشکلی داشته باشه، روش جایگزینی برای از بین نرفتن کانفیگ پس از ریبوت داخل اسکریپت قرار میدم .

**Comment by mr-uranium** [comment]
خیلی ممنون از جواب سریعت و عملکرد عالیت
من از روش Wireguard و روش Sit + Wireguard استفاده کردم در هردو روش بعد از ریبوت سرور، تنظیمات شبکه پاک میشه فقط در روش Sit + Wireguard اون آیپی که از طریق sit ساخته شده باقی میمونه و هنوز کار میکنه ولی اتصال Wireguard از بین رفته .
مشکل از اتصال و پایداری Wireguard هست.

**Comment by mr-uranium** [comment]
بخوام دقیق تر بگم اتصال زیر بعد از ریبوت در سرور Client به طور کامل پاک میشه.

 wireserver1: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1420 qdisc noqueue state UNKNOWN group default qlen 1000
    link/none
    inet6 2001:dc5::1/64 scope global
       valid_lft forever preferred_lft forever

**Comment by Azumi67** [comment]
مشکل رو پیدا کردم . چند دقیقه دیگه آپدیت میدم
