### ISSUE TITLE
Wireguard Tunnel Problem

### ISSUE THREAD

**Issue by mr-uranium** [Azumi67/6TO4-GRE-IPIP-SIT#96]
سلام 
من چندین بار تانل وایرگارد رو در حالت چند سرور خارج و یه سرور ایران تست کردم روی سرور اول به درستی کار مکنه و برای سرور دوم کار نمی کنه.
نمی دونم مشکل از کد هست یا مشکل سرور هست.
اگر تونستی مشکل رو متوجه شی ممنون میشم بهم بگی مشکل از سروره یا اسکریپت مشکل داره

**Comment by Azumi67** [comment]
سلام. نه من خودم به چندین سرور وصل کردم و بعد اپلود کردم. یعنی تست شده. حالا با این حال شما نام گزینه رو بگید من بعدا دوباره تست میکنم

**Comment by mr-uranium** [comment]
![Screenshot 2024-09-08 130700](https://github.com/user-attachments/assets/55f6f1f1-057c-4e2b-a850-b885206e6f2a)
سرور اول به درستی پینک میده ولی سرور دوم نه.
مشکل پاک شده تنظیمات شبکه بعد از ریبوت سرور هم درست شده. خیلی ممنون

**Comment by mr-uranium** [comment]
من از طریق گزینه زیر این ارتباط رو برقرار میکنم.
2. Wireguard - [1]IRAN   Server [5]Kharej Clients

**Comment by Azumi67** [comment]
![1](https://github.com/user-attachments/assets/1dd98a97-42ed-422a-93c2-7ff3af5b59d7)
![2](https://github.com/user-attachments/assets/4b0926f9-3a8a-4f67-86c0-49ad42b8bc2f)

برای من مشکلی نداشت. شما یا کلید ها را به اشتباه وارد کردید یا سرور ایرانتون در کلاینت مربوطه اجازه برقراری ارتباط به wireguard udp را نمیدهد که نیاز است ارتباط اول را با gre6tap یا sit انجام دهید.

**Comment by mr-uranium** [comment]
می خواستم مجدد تست کنم، حالا یه مشکل جدید پیش اومده توی سرور ایران تنظیمات شبکه اجرا نمیشه ولی در سرور Client اجرا میشه
