### ISSUE TITLE
غیر فعال شدن آیپی6 سرور با اجرای تانل anycast

### ISSUE THREAD

**Issue by alamdari86** [Azumi67/6TO4-GRE-IPIP-SIT#97]
سلام و عرض ادب و خسته نباشید

مهندس من وقتی تانل انی کست (anycast) رو اجرا میکنم روی سرور ایران و خارج ، آیپی 6 اصلی خود سرور خارج غیر فعال میشه و پینگ نمیده، آیا راه حلی هست برای این موضوع؟

**Comment by Azumi67** [comment]
سلام . داخل گیت هاب توضیح داده شده که در آن روش‌، default route این مشکل را باید حل‌ کند .
