### ISSUE TITLE
مقدار رم

### ISSUE THREAD

**Issue by TiamaaShah** [Azumi67/6TO4-GRE-IPIP-SIT#99]
سلام 
2 تا سوال داشتم
1 - منظور شما از رم بالا چه مقدار رم هستش؟
2- باید اسکریپت روی سرور ایران و خارج هر دو مشابه باشند .مثلا اگه سرور ایران رم کمی داره ولی سرور خارج رم بالا داره باید روی هر 2 تاش اسکریپت با رم کم رو نصب کرد؟

**Comment by Azumi67** [comment]
سلام برای سرور های با رم کم ، حدودا 500 تا مصرف میکند. اگر نسخه سبک را استفاده کنید تا 200 تا استفاده میکند . فرقی نداره. هر دو اسکریپت یکسان هستند. هر کدام را که دوست دارید استفاده کنید.

**Comment by TiamaaShah** [comment]
با تشکر از شما برای پاسخگویی سریع 
من سرور ایرانم یکیش 1 گیگ رم داره و دومیش 2 گیگ
ولی سرور خارجم 4 گیگ رم داره
پس فرقی توی اسکریپتها از نظر سرعت وجود نداره ؟
مقدار رم مورد نظر برای اسکریپتهای رم بالا چه مقدار هستش؟

**Comment by TiamaaShah** [comment]
فکر کنم منظور شما از 500 مگابایت برای سرور با رم بالا بوده و 200 مگ برای  سرور با رم کم

**Comment by Azumi67** [comment]
بله درسته . هر دو اسکریپت یکسان هستند . مدل لایت کدهای پایه را دارد و بقیه کد ها را call میکند . مدل با رم بالا، همه کد ها در یک فایل پایتون است که بعداً حجیم تر هم می‌شود .
